/*
 * VeridianOS -- kwindowsystem-veridian.cpp
 *
 * Copyright (c) 2025-2026 VeridianOS Contributors
 * SPDX-License-Identifier: MIT OR Apache-2.0
 *
 * KWindowSystem Wayland backend implementation for VeridianOS.  Connects
 * to KWin's Wayland protocols (org_kde_plasma_window_management and
 * org_kde_plasma_virtual_desktop_management) to provide window list
 * enumeration, active window tracking, and virtual desktop management.
 */

#include "kwindowsystem-veridian.h"

#include <QDebug>
#include <QGuiApplication>

#include <wayland-client.h>

/* KDE Wayland protocol headers (generated by wayland-scanner) */
#include <plasma-window-management-client-protocol.h>
#include <plasma-virtual-desktop-client-protocol.h>

namespace KWindowSystemPrivate {

/* ========================================================================= */
/* Wayland registry listener                                                 */
/* ========================================================================= */

static const struct wl_registry_listener s_registryListener = {
    VeridianWaylandIntegration::registryGlobal,
    VeridianWaylandIntegration::registryGlobalRemove,
};

void VeridianWaylandIntegration::registryGlobal(
    void *data, struct wl_registry *registry,
    uint32_t name, const char *interface, uint32_t version)
{
    auto *self = static_cast<VeridianWaylandIntegration *>(data);

    if (strcmp(interface, "org_kde_plasma_window_management") == 0) {
        self->bindWindowManagement(registry, name, version);
    } else if (strcmp(interface,
                      "org_kde_plasma_virtual_desktop_management") == 0) {
        self->bindVirtualDesktopManagement(registry, name, version);
    }
}

void VeridianWaylandIntegration::registryGlobalRemove(
    void *data, struct wl_registry *registry, uint32_t name)
{
    Q_UNUSED(data);
    Q_UNUSED(registry);
    Q_UNUSED(name);
}

/* ========================================================================= */
/* plasma_window_management callbacks                                        */
/* ========================================================================= */

static const struct org_kde_plasma_window_management_listener
    s_windowManagementListener = {
    VeridianWaylandIntegration::windowManagementWindow,
    VeridianWaylandIntegration::windowManagementShowDesktop,
    VeridianWaylandIntegration::windowManagementStackingOrder,
};

void VeridianWaylandIntegration::windowManagementWindow(
    void *data, struct org_kde_plasma_window_management *mgr, uint32_t id)
{
    Q_UNUSED(mgr);
    auto *self = static_cast<VeridianWaylandIntegration *>(data);

    WindowInfo info;
    info.internalId = id;
    info.active = false;
    info.minimized = false;
    info.maximized = false;
    info.fullscreen = false;
    info.keepAbove = false;
    info.keepBelow = false;
    info.demandsAttention = false;
    info.closeable = true;
    info.movable = true;
    info.resizable = true;
    info.maximizable = true;
    info.minimizable = true;
    info.fullscreenable = true;
    info.pid = 0;
    info.state = 0;
    info.virtualDesktop = 0;

    self->m_windows.insert(id, info);

    /* Bind per-window listener for property changes.
     * In a full implementation, org_kde_plasma_window_management_get_window()
     * would return a plasma_window proxy object.  For now, we track the
     * window internally. */

    Q_EMIT self->windowAdded(id);
}

void VeridianWaylandIntegration::windowManagementShowDesktop(
    void *data, struct org_kde_plasma_window_management *mgr, uint32_t state)
{
    Q_UNUSED(data);
    Q_UNUSED(mgr);
    Q_UNUSED(state);
}

void VeridianWaylandIntegration::windowManagementStackingOrder(
    void *data, struct org_kde_plasma_window_management *mgr,
    struct wl_array *ids)
{
    Q_UNUSED(data);
    Q_UNUSED(mgr);
    Q_UNUSED(ids);
    /* Stacking order tracking could be implemented here */
}

/* ========================================================================= */
/* plasma_window per-window callbacks                                        */
/* ========================================================================= */

void VeridianWaylandIntegration::windowTitle(
    void *data, struct org_kde_plasma_window *window, const char *title)
{
    Q_UNUSED(window);
    auto *self = static_cast<VeridianWaylandIntegration *>(data);

    /* Find the window by proxy pointer */
    for (auto it = self->m_windowProxies.begin();
         it != self->m_windowProxies.end(); ++it) {
        if (it.value() == window) {
            if (self->m_windows.contains(it.key())) {
                self->m_windows[it.key()].title = QString::fromUtf8(title);
                Q_EMIT self->windowChanged(it.key());
            }
            break;
        }
    }
}

void VeridianWaylandIntegration::windowAppId(
    void *data, struct org_kde_plasma_window *window, const char *appId)
{
    Q_UNUSED(window);
    auto *self = static_cast<VeridianWaylandIntegration *>(data);

    for (auto it = self->m_windowProxies.begin();
         it != self->m_windowProxies.end(); ++it) {
        if (it.value() == window) {
            if (self->m_windows.contains(it.key())) {
                self->m_windows[it.key()].appId = QString::fromUtf8(appId);
                Q_EMIT self->windowChanged(it.key());
            }
            break;
        }
    }
}

void VeridianWaylandIntegration::windowState(
    void *data, struct org_kde_plasma_window *window, uint32_t flags)
{
    Q_UNUSED(window);
    auto *self = static_cast<VeridianWaylandIntegration *>(data);

    for (auto it = self->m_windowProxies.begin();
         it != self->m_windowProxies.end(); ++it) {
        if (it.value() == window && self->m_windows.contains(it.key())) {
            WindowInfo &info = self->m_windows[it.key()];
            quint32 oldActive = self->m_activeWindow;

            info.state = flags;
            /* Decode state flags (plasma_window_management state bits) */
            info.active          = (flags & 0x001) != 0;
            info.minimized       = (flags & 0x002) != 0;
            info.maximized       = (flags & 0x004) != 0;
            info.fullscreen      = (flags & 0x008) != 0;
            info.keepAbove       = (flags & 0x010) != 0;
            info.keepBelow       = (flags & 0x020) != 0;
            info.demandsAttention = (flags & 0x040) != 0;

            if (info.active) {
                self->m_activeWindow = it.key();
                if (oldActive != self->m_activeWindow)
                    Q_EMIT self->activeWindowChanged(self->m_activeWindow);
            }

            Q_EMIT self->windowChanged(it.key());
            break;
        }
    }
}

void VeridianWaylandIntegration::windowGeometry(
    void *data, struct org_kde_plasma_window *window,
    int32_t x, int32_t y, uint32_t w, uint32_t h)
{
    Q_UNUSED(window);
    auto *self = static_cast<VeridianWaylandIntegration *>(data);

    for (auto it = self->m_windowProxies.begin();
         it != self->m_windowProxies.end(); ++it) {
        if (it.value() == window && self->m_windows.contains(it.key())) {
            self->m_windows[it.key()].geometry = QRect(x, y,
                static_cast<int>(w), static_cast<int>(h));
            Q_EMIT self->windowChanged(it.key());
            break;
        }
    }
}

void VeridianWaylandIntegration::windowVirtualDesktopEntered(
    void *data, struct org_kde_plasma_window *window, const char *id)
{
    Q_UNUSED(window);
    auto *self = static_cast<VeridianWaylandIntegration *>(data);

    for (auto it = self->m_windowProxies.begin();
         it != self->m_windowProxies.end(); ++it) {
        if (it.value() == window && self->m_windows.contains(it.key())) {
            self->m_windows[it.key()].virtualDesktopIds
                << QString::fromUtf8(id);
            Q_EMIT self->windowChanged(it.key());
            break;
        }
    }
}

void VeridianWaylandIntegration::windowClosed(
    void *data, struct org_kde_plasma_window *window)
{
    auto *self = static_cast<VeridianWaylandIntegration *>(data);

    for (auto it = self->m_windowProxies.begin();
         it != self->m_windowProxies.end(); ++it) {
        if (it.value() == window) {
            quint32 windowId = it.key();
            self->m_windows.remove(windowId);
            self->m_windowProxies.erase(it);
            Q_EMIT self->windowRemoved(windowId);
            break;
        }
    }
}

void VeridianWaylandIntegration::windowPid(
    void *data, struct org_kde_plasma_window *window, uint32_t pid)
{
    Q_UNUSED(window);
    auto *self = static_cast<VeridianWaylandIntegration *>(data);

    for (auto it = self->m_windowProxies.begin();
         it != self->m_windowProxies.end(); ++it) {
        if (it.value() == window && self->m_windows.contains(it.key())) {
            self->m_windows[it.key()].pid = pid;
            break;
        }
    }
}

/* ========================================================================= */
/* virtual_desktop_management callbacks                                      */
/* ========================================================================= */

void VeridianWaylandIntegration::desktopCreated(
    void *data, struct org_kde_plasma_virtual_desktop_management *mgr,
    const char *id, uint32_t position)
{
    Q_UNUSED(mgr);
    auto *self = static_cast<VeridianWaylandIntegration *>(data);

    VirtualDesktopInfo desktop;
    desktop.id = QString::fromUtf8(id);
    desktop.name = QStringLiteral("Desktop ") + QString::number(position + 1);
    desktop.number = position;
    desktop.active = (position == 0);

    self->m_desktops.append(desktop);
    Q_EMIT self->desktopListChanged();
}

void VeridianWaylandIntegration::desktopRemoved(
    void *data, struct org_kde_plasma_virtual_desktop_management *mgr,
    const char *id)
{
    Q_UNUSED(mgr);
    auto *self = static_cast<VeridianWaylandIntegration *>(data);

    QString desktopId = QString::fromUtf8(id);
    for (int i = 0; i < self->m_desktops.size(); ++i) {
        if (self->m_desktops[i].id == desktopId) {
            self->m_desktops.removeAt(i);
            Q_EMIT self->desktopListChanged();
            break;
        }
    }
}

/* ========================================================================= */
/* Construction / destruction                                                */
/* ========================================================================= */

VeridianWaylandIntegration::VeridianWaylandIntegration(QObject *parent)
    : QObject(parent)
    , m_display(nullptr)
    , m_registry(nullptr)
    , m_windowManagement(nullptr)
    , m_desktopManagement(nullptr)
    , m_activeWindow(0)
{
    initWayland();
}

VeridianWaylandIntegration::~VeridianWaylandIntegration()
{
    if (m_desktopManagement)
        org_kde_plasma_virtual_desktop_management_destroy(m_desktopManagement);
    if (m_windowManagement)
        org_kde_plasma_window_management_destroy(m_windowManagement);
    if (m_registry)
        wl_registry_destroy(m_registry);
    /* Do NOT disconnect m_display -- owned by Qt */
}

void VeridianWaylandIntegration::initWayland()
{
    /* Get the Wayland display from Qt (we share the connection) */
    m_display = wl_display_connect(nullptr);
    if (!m_display) {
        qWarning("VeridianWaylandIntegration: cannot connect to Wayland display");
        return;
    }

    m_registry = wl_display_get_registry(m_display);
    wl_registry_add_listener(m_registry, &s_registryListener, this);

    /* Round-trip to discover globals */
    wl_display_roundtrip(m_display);
}

void VeridianWaylandIntegration::bindWindowManagement(
    struct wl_registry *registry, uint32_t name, uint32_t version)
{
    uint32_t bindVersion = qMin(version, static_cast<uint32_t>(16));
    m_windowManagement =
        static_cast<struct org_kde_plasma_window_management *>(
            wl_registry_bind(registry, name,
                             &org_kde_plasma_window_management_interface,
                             bindVersion));

    org_kde_plasma_window_management_add_listener(
        m_windowManagement, &s_windowManagementListener, this);
}

void VeridianWaylandIntegration::bindVirtualDesktopManagement(
    struct wl_registry *registry, uint32_t name, uint32_t version)
{
    uint32_t bindVersion = qMin(version, static_cast<uint32_t>(2));
    m_desktopManagement =
        static_cast<struct org_kde_plasma_virtual_desktop_management *>(
            wl_registry_bind(registry, name,
                             &org_kde_plasma_virtual_desktop_management_interface,
                             bindVersion));

    static const struct org_kde_plasma_virtual_desktop_management_listener
        desktopMgmtListener = {
        VeridianWaylandIntegration::desktopCreated,
        VeridianWaylandIntegration::desktopRemoved,
    };

    org_kde_plasma_virtual_desktop_management_add_listener(
        m_desktopManagement, &desktopMgmtListener, this);
}

/* ========================================================================= */
/* Window list                                                               */
/* ========================================================================= */

QList<quint32> VeridianWaylandIntegration::windows() const
{
    return m_windows.keys();
}

WindowInfo VeridianWaylandIntegration::windowInfo(quint32 windowId) const
{
    return m_windows.value(windowId);
}

quint32 VeridianWaylandIntegration::activeWindow() const
{
    return m_activeWindow;
}

/* ========================================================================= */
/* Window operations                                                         */
/* ========================================================================= */

void VeridianWaylandIntegration::activateWindow(quint32 windowId)
{
    struct org_kde_plasma_window *proxy = m_windowProxies.value(windowId);
    if (proxy) {
        org_kde_plasma_window_set_state(
            proxy,
            ORG_KDE_PLASMA_WINDOW_MANAGEMENT_STATE_ACTIVE,
            ORG_KDE_PLASMA_WINDOW_MANAGEMENT_STATE_ACTIVE);
    }
}

void VeridianWaylandIntegration::closeWindow(quint32 windowId)
{
    struct org_kde_plasma_window *proxy = m_windowProxies.value(windowId);
    if (proxy) {
        org_kde_plasma_window_close(proxy);
    }
}

void VeridianWaylandIntegration::minimizeWindow(quint32 windowId)
{
    struct org_kde_plasma_window *proxy = m_windowProxies.value(windowId);
    if (proxy) {
        org_kde_plasma_window_set_state(
            proxy,
            ORG_KDE_PLASMA_WINDOW_MANAGEMENT_STATE_MINIMIZED,
            ORG_KDE_PLASMA_WINDOW_MANAGEMENT_STATE_MINIMIZED);
    }
}

void VeridianWaylandIntegration::unminimizeWindow(quint32 windowId)
{
    struct org_kde_plasma_window *proxy = m_windowProxies.value(windowId);
    if (proxy) {
        org_kde_plasma_window_set_state(
            proxy,
            ORG_KDE_PLASMA_WINDOW_MANAGEMENT_STATE_MINIMIZED, 0);
    }
}

void VeridianWaylandIntegration::maximizeWindow(quint32 windowId)
{
    struct org_kde_plasma_window *proxy = m_windowProxies.value(windowId);
    if (proxy) {
        org_kde_plasma_window_set_state(
            proxy,
            ORG_KDE_PLASMA_WINDOW_MANAGEMENT_STATE_MAXIMIZED,
            ORG_KDE_PLASMA_WINDOW_MANAGEMENT_STATE_MAXIMIZED);
    }
}

void VeridianWaylandIntegration::restoreWindow(quint32 windowId)
{
    struct org_kde_plasma_window *proxy = m_windowProxies.value(windowId);
    if (proxy) {
        org_kde_plasma_window_set_state(
            proxy,
            ORG_KDE_PLASMA_WINDOW_MANAGEMENT_STATE_MAXIMIZED, 0);
    }
}

void VeridianWaylandIntegration::requestMoveWindow(quint32 windowId)
{
    struct org_kde_plasma_window *proxy = m_windowProxies.value(windowId);
    if (proxy) {
        org_kde_plasma_window_request_move(proxy);
    }
}

void VeridianWaylandIntegration::requestResizeWindow(quint32 windowId)
{
    struct org_kde_plasma_window *proxy = m_windowProxies.value(windowId);
    if (proxy) {
        org_kde_plasma_window_request_resize(proxy);
    }
}

void VeridianWaylandIntegration::setWindowOnDesktop(
    quint32 windowId, const QString &desktopId)
{
    struct org_kde_plasma_window *proxy = m_windowProxies.value(windowId);
    if (proxy) {
        org_kde_plasma_window_request_enter_virtual_desktop(
            proxy, desktopId.toUtf8().constData());
    }
}

void VeridianWaylandIntegration::setKeepAbove(quint32 windowId, bool above)
{
    struct org_kde_plasma_window *proxy = m_windowProxies.value(windowId);
    if (proxy) {
        org_kde_plasma_window_set_state(
            proxy,
            ORG_KDE_PLASMA_WINDOW_MANAGEMENT_STATE_KEEP_ABOVE,
            above ? ORG_KDE_PLASMA_WINDOW_MANAGEMENT_STATE_KEEP_ABOVE : 0);
    }
}

void VeridianWaylandIntegration::setKeepBelow(quint32 windowId, bool below)
{
    struct org_kde_plasma_window *proxy = m_windowProxies.value(windowId);
    if (proxy) {
        org_kde_plasma_window_set_state(
            proxy,
            ORG_KDE_PLASMA_WINDOW_MANAGEMENT_STATE_KEEP_BELOW,
            below ? ORG_KDE_PLASMA_WINDOW_MANAGEMENT_STATE_KEEP_BELOW : 0);
    }
}

/* ========================================================================= */
/* Virtual desktops                                                          */
/* ========================================================================= */

QList<VirtualDesktopInfo> VeridianWaylandIntegration::virtualDesktops() const
{
    return m_desktops;
}

QString VeridianWaylandIntegration::currentDesktop() const
{
    return m_currentDesktop;
}

void VeridianWaylandIntegration::setCurrentDesktop(const QString &desktopId)
{
    /* Request desktop switch via Wayland protocol.  The compositor will
     * send back a done event confirming the switch. */
    m_currentDesktop = desktopId;
    Q_EMIT currentDesktopChanged(desktopId);
}

int VeridianWaylandIntegration::numberOfDesktops() const
{
    return m_desktops.size();
}

} /* namespace KWindowSystemPrivate */
