# Rust formatting configuration

# Version of formatting rules
edition = "2021"

# Line width
max_width = 100

# Use Unix line endings
newline_style = "Unix"

# Use field init shorthand
use_field_init_shorthand = true

# Use spaces for indentation
hard_tabs = false
tab_spaces = 4

# Reorder imports and modules
reorder_imports = true
reorder_modules = true

# Format code in doc comments
format_code_in_doc_comments = true

# Format macro bodies
format_macro_bodies = true

# Format string literals
format_strings = true

# Normalize comments
normalize_comments = true

# Wrap comments at max_width
wrap_comments = true

# Merge multiple imports from same crate
imports_granularity = "Crate"

# Group imports
group_imports = "StdExternalCrate"

# Error on formatting errors
error_on_line_overflow = false
error_on_unformatted = false

# Report formatting errors
report_todo = "Always"
report_fixme = "Always"