# shellcheck shell=bash
# Cross-build environment and helpers shared by the tools/cross phase
# scripts (sourced, after veridian-paths.sh). The sourcing script defines
# log(), die(), BUILD_DIR (its build tree) and JOBS.
#
# Every package is compiled with the musl cross toolchain
# (build-musl-toolchain.sh) as shared libraries (ADR 0010), configured for
# /usr on the target and staged into the sysroot with DESTDIR, so the paths
# a library reads at run time are target paths, never the build host's
# sysroot.

SYSROOT="${VERIDIAN_SYSROOT}"
HOST="${VERIDIAN_TARGET}"
# CMake toolchain files: the base one, and the one for the Qt/KDE phases
# (used by the sourcing scripts).
CMAKE_TOOLCHAIN_BASE="${VERIDIAN_CROSS_DIR:?}/cmake-toolchain-veridian-deps.cmake"
# shellcheck disable=SC2034
CMAKE_TOOLCHAIN_KDE="${VERIDIAN_CROSS_DIR}/cmake-toolchain-veridian.cmake"

export CC="${VERIDIAN_CC}"
export CXX="${VERIDIAN_CXX}"
export AR="${HOST}-ar"
export RANLIB="${HOST}-ranlib"
export NM="${HOST}-nm"
export STRIP="${HOST}-strip"
export CFLAGS="-O2 -fPIC"
export CXXFLAGS="-O2 -fPIC"
# Only the sysroot's .pc files, with their /usr paths placed in the sysroot.
export PKG_CONFIG_LIBDIR="${SYSROOT}/usr/lib/pkgconfig:${SYSROOT}/usr/share/pkgconfig"
export PKG_CONFIG_SYSROOT_DIR="${SYSROOT}"
unset PKG_CONFIG_PATH
export PKG_CONFIG="pkg-config"

# Autotools configure arguments (used by the sourcing scripts).
# shellcheck disable=SC2034
COMMON_CONFIGURE=(
    --host="${HOST}"
    --prefix=/usr
    --sysconfdir=/etc
    --localstatedir=/var
    --enable-shared
    --disable-static
)

# The launcher for VeridianOS programs the build runs on this host (meson's
# exe_wrapper, CMake's emulator and wrappers of imported tools): dynamic
# programs go through musl's loader with the sysroot's libraries only
# (musl's default path would reach the host's glibc libraries in /usr/lib),
# Qt's plugins from the sysroot; static ones run directly.
mkdir -p "$(dirname "${VERIDIAN_RUN_TARGET}")"
cat > "${VERIDIAN_RUN_TARGET}.tmp" <<RUNEOF
#!/bin/sh
# Generated by tools/cross/lib/cross-env.sh.
prog="\$1"
shift
if "${VERIDIAN_TOOLCHAIN}/bin/${HOST}-readelf" -l "\$prog" 2>/dev/null | grep -q 'program interpreter'; then
    QT_PLUGIN_PATH="${SYSROOT}/usr/lib/qt6/plugins" exec "${SYSROOT}/usr/lib/libc.so" \\
        --library-path "${SYSROOT}/usr/lib" "\$prog" "\$@"
fi
exec "\$prog" "\$@"
RUNEOF
chmod 755 "${VERIDIAN_RUN_TARGET}.tmp"
mv "${VERIDIAN_RUN_TARGET}.tmp" "${VERIDIAN_RUN_TARGET}"

# The meson cross file with this machine's paths.
mkdir -p "${BUILD_DIR:?}"
MESON_CROSS="${BUILD_DIR}/meson-cross-veridian.txt"
sed -e "s|@SYSROOT@|${SYSROOT}|g" \
    -e "s|@TOOLCHAIN@|${VERIDIAN_TOOLCHAIN}|g" \
    -e "s|@TARGET@|${HOST}|g" \
    -e "s|@RUN_TARGET@|${VERIDIAN_RUN_TARGET}|g" \
    "${VERIDIAN_CROSS_DIR}/meson-cross-veridian.txt" > "${MESON_CROSS}"

# installed LIB NAME: whether LIB (under usr/lib) is already staged.
installed() { [[ -f "${SYSROOT}/usr/lib/$1" ]] && log "$2: already installed."; }

# fetch FILE URL DIR SHA256: download FILE into the source cache once,
# check it, and extract a fresh DIR (a tree left from an earlier build
# would carry its configuration and patches).
fetch() {
    local file="$1" url="$2" dir="$3" sha="$4"
    local tarball="${VERIDIAN_SOURCES}/${file}"
    if [[ ! -f "${tarball}" ]]; then
        log "Downloading ${file}..."
        curl -fsSL -o "${tarball}.part" "${url}" && [[ -s "${tarball}.part" ]] \
            || { rm -f "${tarball}.part"; die "download failed: ${url}"; }
        mv "${tarball}.part" "${tarball}"
    fi
    echo "${sha}  ${tarball}" | sha256sum -c --quiet - || die "${file}: checksum mismatch"
    rm -rf "${BUILD_DIR:?}/${dir}"
    tar -xf "${tarball}" -C "${BUILD_DIR}"
}

# listed_sha256 LIST FILE: FILE's checksum from a sha256sum-format list in
# checksums/ (for release sets with many tarballs, such as KDE's).
listed_sha256() {
    local sha
    sha="$(awk -v f="$2" '$2 == f { print $1 }' "${VERIDIAN_CROSS_DIR}/checksums/$1")"
    [[ -n "${sha}" ]] || die "$2 has no checksum in checksums/$1"
    echo "${sha}"
}

# replace_once FILE OLD NEW: an exact source edit that must match once
# (or already be applied).
replace_once() {
    python3 -I - "$@" <<'PYEOF' || die "failed to patch $1"
import sys
path, old, new = sys.argv[1:4]
s = open(path).read()
if new in s and old not in s:
    sys.exit(0)
if s.count(old) != 1:
    sys.exit(f"{path}: expected one match")
open(path, "w").write(s.replace(old, new))
PYEOF
}

# apply_patches DIR SRC: DIR's *.patch files, in order, to the freshly
# extracted tree SRC.
apply_patches() {
    local patch
    for patch in "$1"/*.patch; do
        [[ -f "${patch}" ]] || continue
        log "Applying $(basename "${patch}")..."
        patch -d "$2" -p1 --forward --quiet < "${patch}" || die "failed to apply $(basename "${patch}")"
    done
}

# refresh_config_scripts SRC: replace an old package's config.sub and
# config.guess with the host automake's, which know current targets
# (x86_64-*-linux-musl), as distributions do.
refresh_config_scripts() {
    local dir file
    dir="$(automake --print-libdir)" || die "automake not found"
    while IFS= read -r -d '' file; do
        install -m755 "${dir}/$(basename "${file}")" "${file}"
    done < <(find "$1" \( -name config.sub -o -name config.guess \) -print0)
}

# Autotools (run in the configured tree): build, stage into the sysroot,
# and drop libtool archives. A .la file names its libdir (/usr/lib), which
# a later libtool link would take as the build host's /usr/lib.
make_install() {
    make -j"${JOBS}"
    make install DESTDIR="${SYSROOT}"
    rm -f "${SYSROOT}"/usr/lib/*.la
}

# meson without the target pkg-config environment (for autotools): the
# cross file gives meson the sysroot and search path for the target, and
# a native dependency (wayland-scanner) must not be looked up in the
# sysroot.
meson_cross() {
    env -u PKG_CONFIG -u PKG_CONFIG_LIBDIR -u PKG_CONFIG_SYSROOT_DIR "$@"
}

# meson_build SRC BUILD [OPTIONS...]: cross build for /usr, staged.
meson_build() {
    local src="$1" bld="$2"
    shift 2
    rm -rf "${bld}"
    meson_cross meson setup "${bld}" "${src}" \
        --cross-file="${MESON_CROSS}" \
        --prefix=/usr \
        --libdir=lib \
        --buildtype=release \
        --default-library=shared \
        "$@"
    meson_cross ninja -C "${bld}" -j"${JOBS}"
    DESTDIR="${SYSROOT}" meson_cross ninja -C "${bld}" install
}

# cmake_build SRC BUILD [OPTIONS...]: cross build for /usr, staged, with
# CMAKE_TOOLCHAIN (default: the base toolchain file).
cmake_build() {
    local src="$1" bld="$2"
    shift 2
    rm -rf "${bld}"
    cmake -S "${src}" -B "${bld}" \
        -DCMAKE_TOOLCHAIN_FILE="${CMAKE_TOOLCHAIN:-${CMAKE_TOOLCHAIN_BASE}}" \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
        "$@"
    cmake --build "${bld}" -j"${JOBS}"
    DESTDIR="${SYSROOT}" cmake --install "${bld}"
}

[[ -x "${CC}" ]] || die "no cross compiler at ${CC} (run build-musl-toolchain.sh)"
