/*
 * VeridianOS -- nm-dns.cpp
 *
 * Copyright (c) 2025-2026 VeridianOS Contributors
 * SPDX-License-Identifier: MIT OR Apache-2.0
 *
 * DNS configuration backend for the NetworkManager shim.
 *
 * Manages /etc/resolv.conf with nameserver and search domain entries.
 * Backs up the original resolv.conf on first modification and can
 * restore it on shutdown.  Flushes the kernel DNS cache on connection
 * changes to ensure stale entries are not served.
 */

#include "nm-dns.h"

#include <QDebug>
#include <QFile>
#include <QFileInfo>
#include <QTextStream>
#include <QDateTime>

#include <cstring>
#include <cstdio>

/* ========================================================================= */
/* Constants                                                                 */
/* ========================================================================= */

static const char *RESOLV_CONF      = "/etc/resolv.conf";
static const char *RESOLV_CONF_BAK  = "/etc/resolv.conf.nm-backup";

/* VeridianOS kernel DNS cache flush path */
static const char *DNS_CACHE_FLUSH  = "/proc/net/dns_cache_flush";

/* ========================================================================= */
/* Helper: back up the original resolv.conf (once)                           */
/* ========================================================================= */

static bool s_backup_done = false;

static void backup_resolv_conf(void)
{
    if (s_backup_done)
        return;

    if (QFileInfo::exists(QString::fromLatin1(RESOLV_CONF))) {
        QFile::copy(QString::fromLatin1(RESOLV_CONF),
                    QString::fromLatin1(RESOLV_CONF_BAK));
        qDebug("NM-DNS: backed up %s to %s", RESOLV_CONF, RESOLV_CONF_BAK);
    }

    s_backup_done = true;
}

/* ========================================================================= */
/* Set DNS servers                                                           */
/* ========================================================================= */

bool nm_dns_set_servers(const char **servers, uint32_t server_count,
                        const char **domains, uint32_t domain_count)
{
    if (!servers || server_count == 0)
        return false;

    if (server_count > NM_DNS_MAX_SERVERS)
        server_count = NM_DNS_MAX_SERVERS;
    if (domain_count > NM_DNS_MAX_DOMAINS)
        domain_count = NM_DNS_MAX_DOMAINS;

    backup_resolv_conf();

    QFile file(QString::fromLatin1(RESOLV_CONF));
    if (!file.open(QIODevice::WriteOnly | QIODevice::Text | QIODevice::Truncate)) {
        qWarning("NM-DNS: cannot write %s: %s",
                 RESOLV_CONF, qPrintable(file.errorString()));
        return false;
    }

    QTextStream out(&file);

    /* Header */
    out << QStringLiteral("# Generated by VeridianOS NetworkManager shim\n");
    out << QStringLiteral("# %1\n").arg(
        QDateTime::currentDateTime().toString(Qt::ISODate));
    out << QStringLiteral("#\n");

    /* Search domains */
    if (domains && domain_count > 0) {
        out << QStringLiteral("search");
        for (uint32_t i = 0; i < domain_count; ++i) {
            if (domains[i])
                out << QStringLiteral(" %1").arg(QString::fromLatin1(domains[i]));
        }
        out << QStringLiteral("\n");
    }

    /* Nameservers */
    for (uint32_t i = 0; i < server_count; ++i) {
        if (servers[i])
            out << QStringLiteral("nameserver %1\n").arg(QString::fromLatin1(servers[i]));
    }

    out << QStringLiteral("\n");
    file.close();

    qDebug("NM-DNS: wrote %s with %u nameservers, %u search domains",
           RESOLV_CONF, server_count, domain_count);

    /* Flush cache after updating config */
    nm_dns_flush_cache();

    return true;
}

/* ========================================================================= */
/* Cache flush                                                               */
/* ========================================================================= */

void nm_dns_flush_cache(void)
{
    /* VeridianOS kernel exposes a proc file to flush the DNS cache */
    QFile file(QString::fromLatin1(DNS_CACHE_FLUSH));
    if (file.open(QIODevice::WriteOnly)) {
        file.write("1");
        file.close();
        qDebug("NM-DNS: flushed DNS cache via %s", DNS_CACHE_FLUSH);
    } else {
        /* Fallback: the kernel dns.rs module may not expose this yet */
        qDebug("NM-DNS: DNS cache flush not available (non-fatal)");
    }
}

/* ========================================================================= */
/* Restore resolv.conf                                                       */
/* ========================================================================= */

bool nm_dns_restore_resolv_conf(void)
{
    if (!QFileInfo::exists(QString::fromLatin1(RESOLV_CONF_BAK))) {
        qDebug("NM-DNS: no backup to restore");
        return false;
    }

    /* Remove current and restore backup */
    QFile::remove(QString::fromLatin1(RESOLV_CONF));

    if (QFile::copy(QString::fromLatin1(RESOLV_CONF_BAK),
                    QString::fromLatin1(RESOLV_CONF))) {
        QFile::remove(QString::fromLatin1(RESOLV_CONF_BAK));
        qDebug("NM-DNS: restored %s from backup", RESOLV_CONF);
        s_backup_done = false;
        return true;
    }

    qWarning("NM-DNS: failed to restore %s", RESOLV_CONF);
    return false;
}
