// x86_64-specific bootstrap output functions
//
// Uses early_println! for serial output during boot, before the full
// kernel print infrastructure is available.  The stage functions are
// generated by the shared `define_bootstrap_stages!` macro to avoid
// duplicating identical stage messages across architectures.

/// Print a bootstrap message via x86_64 early serial output.
macro_rules! x86_boot_print {
    ($s:expr) => {
        crate::early_println!($s)
    };
}

crate::define_bootstrap_stages!(x86_boot_print);
