#!/usr/bin/env python3
"""Generate the VeridianOS system call numbers from one source (ADR 0009).

Inputs:
    abi/syscalls.map          kernel variant -> Linux name or private number
    abi/linux/syscall_64.tbl  Linux x86_64 numbers (vendored, v7.2)

Outputs (checked in; never edit them by hand):
    kernel/src/syscall/numbers.rs           the Syscall enum and its decoder
    userland/libc/include/veridian/sysno.h  SYS_* for the native libc
    userland/abi/syscall_numbers.rs         SYS_* for rust-std and vsh
    docs/compat/SYSCALL-NUMBERS.md          the table, for people

Usage:
    tools/compat/gen_syscalls.py           write the outputs
    tools/compat/gen_syscalls.py --check   exit 1 if any output is stale
"""

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
MAP = REPO / "abi/syscalls.map"
TBL = REPO / "abi/linux/syscall_64.tbl"
OUT_RS = REPO / "kernel/src/syscall/numbers.rs"
OUT_H = REPO / "userland/libc/include/veridian/sysno.h"
OUT_USER_RS = REPO / "userland/abi/syscall_numbers.rs"
OUT_MD = REPO / "docs/compat/SYSCALL-NUMBERS.md"

PRIVATE_BASE = 1024
HEADER = "Generated by tools/compat/gen_syscalls.py from abi/syscalls.map and\nabi/linux/syscall_64.tbl. Do not edit; edit the map and regenerate."


def fail(msg):
    sys.exit(f"gen_syscalls: {msg}")


def read_linux_table():
    table = {}
    for line in TBL.read_text().splitlines():
        if not line.strip() or line.startswith("#"):
            continue
        fields = line.split()
        if len(fields) >= 3 and fields[1] in ("common", "64"):
            table[fields[2]] = int(fields[0])
    return table


def upper_snake(name):
    return re.sub(r"(?<=[a-z0-9])(?=[A-Z])", "_", name).upper()


def camel(linux_name):
    return "".join(p[:1].upper() + p[1:] for p in linux_name.split("_"))


def read_map(linux):
    entries, group = [], None
    seen_variants, seen_numbers = set(), {}
    for lineno, line in enumerate(MAP.read_text().splitlines(), 1):
        if line.startswith("## "):
            group = line[3:].strip()
            continue
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        fields = line.split()
        if len(fields) == 3 and fields[1] == "private":
            variant, linux_name, number = fields[0], None, int(fields[2])
            if number < PRIVATE_BASE:
                fail(f"line {lineno}: private number {number} is below {PRIVATE_BASE}")
            const = "SYS_" + upper_snake(variant)
        elif len(fields) == 1:
            linux_name = fields[0]
            if linux_name not in linux:
                fail(f"line {lineno}: {linux_name} is not an x86_64 Linux syscall")
            variant, number = camel(linux_name), linux[linux_name]
            const = "SYS_" + linux_name
        else:
            fail(f"line {lineno}: expected '<linux name>' or '<Variant> private <n>'")
        if variant in seen_variants:
            fail(f"line {lineno}: {variant} listed twice")
        if number in seen_numbers:
            fail(f"line {lineno}: {variant} reuses number {number} of {seen_numbers[number]}")
        seen_variants.add(variant)
        seen_numbers[number] = variant
        entries.append({
            "variant": variant,
            "number": number,
            "linux": linux_name,
            "group": group,
            "const": const,
        })
    return entries


def gen_rust(entries):
    out = [f"//! System call numbers ({len(entries)} calls; ADR 0009).", "//!"]
    out += [f"//! {l}" for l in HEADER.splitlines()]
    out += [
        "//!",
        "//! A call that Linux also has uses its Linux x86_64 number; a call only",
        f"//! VeridianOS has uses a private number from {PRIVATE_BASE} up.",
        "",
        "/// System call numbers",
        "#[repr(usize)]",
        "#[derive(Debug, Clone, Copy, PartialEq, Eq)]",
        "pub enum Syscall {",
    ]
    group = None
    for e in entries:
        if e["group"] != group:
            if group is not None:
                out.append("")
            group = e["group"]
            out.append(f"    // {group}")
        doc = f"Linux `{e['linux']}`" if e["linux"] else "VeridianOS only"
        out.append(f"    /// {doc}")
        out.append(f"    {e['variant']} = {e['number']},")
    out.append("}")
    out += [
        "",
        "impl TryFrom<usize> for Syscall {",
        "    type Error = ();",
        "",
        "    fn try_from(value: usize) -> Result<Self, Self::Error> {",
        "        match value {",
    ]
    for e in sorted(entries, key=lambda e: e["number"]):
        out.append(f"            {e['number']} => Ok(Syscall::{e['variant']}),")
    out += [
        "            _ => Err(()),",
        "        }",
        "    }",
        "}",
        "",
        "impl Syscall {",
        "    /// The Linux name of this call, or `None` for a VeridianOS-only call.",
        "    pub const fn linux_name(self) -> Option<&'static str> {",
        "        match self {",
    ]
    for e in entries:
        value = f'Some("{e["linux"]}")' if e["linux"] else "None"
        out.append(f"            Syscall::{e['variant']} => {value},")
    out += [
        "        }",
        "    }",
        "}",
        "",
        "/// Every call, for table checks.",
        "#[cfg(test)]",
        "pub(crate) const ALL: &[Syscall] = &[",
    ]
    for e in entries:
        out.append(f"    Syscall::{e['variant']},")
    out += ["];", ""]
    return "\n".join(out)


def gen_c(entries):
    out = ["/*", " * VeridianOS -- <veridian/sysno.h>: system call numbers (ADR 0009).", " *"]
    out += [f" * {l}" for l in HEADER.splitlines()]
    out += [
        " *",
        " * A call Linux also has is SYS_<linux name> (SYS_write); a call only",
        " * VeridianOS has is SYS_<NAME> (SYS_IPC_SEND).",
        " */",
        "",
        "#ifndef _VERIDIAN_SYSNO_H",
        "#define _VERIDIAN_SYSNO_H",
        "",
    ]
    group = None
    for e in entries:
        if e["group"] != group:
            group = e["group"]
            out += [f"/* {group} */"]
        out.append(f"#define {e['const']:<32} {e['number']}")
    out += ["", "#endif /* _VERIDIAN_SYSNO_H */", ""]
    return "\n".join(out)


def gen_user_rust(entries):
    out = ["// System call numbers for VeridianOS user programs (ADR 0009)."]
    out += [f"// {l}" for l in HEADER.splitlines()]
    out += [
        "//",
        "// Used with include!, which takes items only, so the attribute sits on",
        "// a module: `include!(\".../syscall_numbers.rs\"); pub use sysno::*;`",
        "",
        "#[allow(dead_code, non_upper_case_globals)]",
        "pub mod sysno {",
    ]
    for e in entries:
        out.append(f"    pub const {e['const']}: usize = {e['number']};")
    out += ["}", ""]
    return "\n".join(out)


def gen_md(entries):
    linux = sum(1 for e in entries if e["linux"])
    out = [
        "# VeridianOS system call numbers",
        "",
        "Generated by `tools/compat/gen_syscalls.py` from `abi/syscalls.map`; do not edit.",
        "",
        f"{len(entries)} calls: {linux} use their Linux x86_64 number and name (ADR 0009), "
        f"{len(entries) - linux} are VeridianOS calls numbered from {PRIVATE_BASE}. "
        "C programs get the numbers from `<veridian/sysno.h>`, Rust programs from "
        "`userland/abi/syscall_numbers.rs`. What each Linux call implements, and how fully, "
        "is in `LINUX-SYSCALL-COVERAGE.md`.",
    ]
    group = None
    for e in entries:
        if e["group"] != group:
            group = e["group"]
            out += ["", f"## {group}", "", "| Number | Constant | Kernel variant |", "|---|---|---|"]
        out.append(f"| {e['number']} | `{e['const']}` | `{e['variant']}` |")
    out.append("")
    return "\n".join(out)


def main():
    check = "--check" in sys.argv[1:]
    entries = read_map(read_linux_table())
    outputs = {
        OUT_RS: gen_rust(entries),
        OUT_H: gen_c(entries),
        OUT_USER_RS: gen_user_rust(entries),
        OUT_MD: gen_md(entries),
    }
    stale = []
    for path, text in outputs.items():
        current = path.read_text() if path.exists() else None
        if current == text:
            continue
        if check:
            stale.append(path.relative_to(REPO))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text)
            print(f"wrote {path.relative_to(REPO)}")
    if stale:
        fail("stale (run tools/compat/gen_syscalls.py): " + ", ".join(map(str, stale)))


if __name__ == "__main__":
    main()
