# VeridianOS tools other packages installed, run on the build host.
#
# Loaded into every Qt/KDE CMake project (CMAKE_PROJECT_INCLUDE, set by
# cmake-toolchain-veridian.cmake). Packages run tools that earlier packages
# installed into the sysroot -- KConfig's kconfig_compiler, for instance --
# as imported executables (KF6::kconfig_compiler_kf6). Those are VeridianOS
# programs, dynamically linked against the sysroot's libraries (ADR 0010),
# which the build host cannot start directly, and CMake applies its
# cross-compiling emulator only to executables the project builds itself.
#
# After each find_package(), every imported executable it created whose
# file is in the sysroot is pointed at a small script that runs that file
# through the target launcher (${VERIDIAN_RUN_TARGET}, lib/cross-env.sh).
# Commands naming the target ($<TARGET_FILE:...>, or the target name) then
# run the wrapper. Executables from elsewhere (the host Qt's moc, ...) are
# left as they are.

include_guard(GLOBAL)

set(_VERIDIAN_TT_SYSROOT "${CMAKE_SYSROOT}")
set(_VERIDIAN_TT_DIR "${CMAKE_BINARY_DIR}/veridian-target-tools")

function(_veridian_tt_wrap target)
    get_target_property(type ${target} TYPE)
    get_target_property(imported ${target} IMPORTED)
    if(NOT type STREQUAL "EXECUTABLE" OR NOT imported)
        return()
    endif()
    get_target_property(done ${target} _VERIDIAN_TT_DONE)
    if(done)
        return()
    endif()
    string(LENGTH "${_VERIDIAN_TT_SYSROOT}/" root_len)
    foreach(prop IMPORTED_LOCATION IMPORTED_LOCATION_RELEASE IMPORTED_LOCATION_NOCONFIG
                 IMPORTED_LOCATION_RELWITHDEBINFO IMPORTED_LOCATION_DEBUG)
        get_target_property(location ${target} ${prop})
        if(NOT location)
            continue()
        endif()
        string(SUBSTRING "${location}" 0 ${root_len} head)
        if(NOT head STREQUAL "${_VERIDIAN_TT_SYSROOT}/")
            continue()
        endif()
        get_filename_component(name "${location}" NAME)
        set(wrapper "${_VERIDIAN_TT_DIR}/${name}")
        file(WRITE "${wrapper}"
             "#!/bin/sh\n# ${target}: generated by tools/cross/cmake/VeridianTargetTools.cmake\n"
             "exec \"${VERIDIAN_RUN_TARGET}\" \"${location}\" \"$@\"\n")
        file(CHMOD "${wrapper}" PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE
             GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE)
        set_property(TARGET ${target} PROPERTY ${prop} "${wrapper}")
    endforeach()
    set_property(TARGET ${target} PROPERTY _VERIDIAN_TT_DONE TRUE)
endfunction()

function(_veridian_tt_wrap_new before after)
    foreach(target IN LISTS after)
        if(NOT target IN_LIST before)
            _veridian_tt_wrap(${target})
        endif()
    endforeach()
endfunction()

# A macro, so that find_package's results land in the caller's scope as
# usual; the previous find_package stays reachable as _find_package.
macro(find_package)
    get_property(_veridian_tt_before DIRECTORY PROPERTY IMPORTED_TARGETS)
    _find_package(${ARGV})
    get_property(_veridian_tt_after DIRECTORY PROPERTY IMPORTED_TARGETS)
    _veridian_tt_wrap_new("${_veridian_tt_before}" "${_veridian_tt_after}")
endmacro()
