// AArch64-specific bootstrap output functions
//
// Uses direct UART writes (bypassing LLVM loop compilation bugs) for
// serial output during boot.  The stage functions are generated by the
// shared `define_bootstrap_stages!` macro to avoid duplicating identical
// stage messages across architectures.

/// Print a bootstrap message via AArch64 direct UART.
///
/// Appends a newline to match the behavior of println-style macros
/// used on other architectures.
macro_rules! aarch64_boot_print {
    ($s:expr) => {
        // SAFETY: uart_write_str writes to the QEMU virt machine UART at
        // 0x0900_0000.  This address is valid and mapped during early boot
        // on the AArch64 QEMU virt platform.  The function only performs
        // MMIO register writes and cannot cause memory corruption.
        unsafe {
            crate::arch::aarch64::direct_uart::uart_write_str(concat!($s, "\n"));
        }
    };
}

crate::define_bootstrap_stages!(aarch64_boot_print);
