/*
 * VeridianOS -- kwin-veridian-protocols.cpp
 *
 * Copyright (c) 2025-2026 VeridianOS Contributors
 * SPDX-License-Identifier: MIT OR Apache-2.0
 *
 * Server-side implementation of KDE-specific Wayland protocols for
 * KWin on VeridianOS.  These protocols enable the Plasma Desktop shell,
 * taskbar, system settings, and other KDE components to communicate
 * with the compositor.
 *
 * Protocol versions:
 *   - org_kde_plasma_shell v6
 *   - org_kde_plasma_window_management v16
 *   - org_kde_kwin_server_decoration_manager v1
 *   - org_kde_kwin_blur_manager v1
 *   - org_kde_kwin_dpms v1
 *   - org_kde_kwin_outputdevice v2
 *   - org_kde_kwin_outputmanagement v2
 */

#include "kwin-veridian-protocols.h"
#include "kwin-veridian-platform.h"

#include <QDebug>
#include <QByteArray>

#include <wayland-server-core.h>
#include <string.h>

/* KDE Wayland protocol headers (generated by wayland-scanner from .xml) */
#include <plasma-shell-server-protocol.h>
#include <plasma-window-management-server-protocol.h>
#include <server-decoration-server-protocol.h>
#include <blur-server-protocol.h>
#include <dpms-server-protocol.h>
#include <outputdevice-server-protocol.h>
#include <outputmanagement-server-protocol.h>

namespace KWin {

/* ========================================================================= */
/* VeridianPlasmaShellInterface                                              */
/* ========================================================================= */

/* Plasma shell surface interface operations */
static const struct org_kde_plasma_surface_interface s_plasmaSurfaceImpl = {
    /* destroy */
    [](struct wl_client *, struct wl_resource *resource) {
        wl_resource_destroy(resource);
    },
    /* set_output */
    [](struct wl_client *, struct wl_resource *, struct wl_resource *) {},
    /* set_position */
    VeridianPlasmaShellInterface::shellSurfaceSetPosition,
    /* set_role */
    VeridianPlasmaShellInterface::shellSurfaceSetRole,
    /* set_panel_behavior */
    VeridianPlasmaShellInterface::shellSurfaceSetPanelBehavior,
    /* set_skip_taskbar */
    VeridianPlasmaShellInterface::shellSurfaceSetSkipTaskbar,
    /* set_skip_switcher */
    VeridianPlasmaShellInterface::shellSurfaceSetSkipSwitcher,
};

/* Plasma shell manager interface operations */
static const struct org_kde_plasma_shell_interface s_plasmaShellImpl = {
    /* get_surface */
    VeridianPlasmaShellInterface::getShellSurface,
};

VeridianPlasmaShellInterface::VeridianPlasmaShellInterface(
    struct wl_display *display, QObject *parent)
    : QObject(parent)
    , m_display(display)
    , m_global(nullptr)
{
    m_global = wl_global_create(display, &org_kde_plasma_shell_interface,
                                6, this, bind);
    if (!m_global) {
        qWarning("VeridianPlasmaShell: wl_global_create failed");
    }
}

VeridianPlasmaShellInterface::~VeridianPlasmaShellInterface()
{
    qDeleteAll(m_surfaces);
    if (m_global)
        wl_global_destroy(m_global);
}

void VeridianPlasmaShellInterface::bind(struct wl_client *client, void *data,
                                         uint32_t version, uint32_t id)
{
    Q_UNUSED(data);
    struct wl_resource *resource = wl_resource_create(client,
        &org_kde_plasma_shell_interface,
        static_cast<int>(qMin(version, 6u)), id);
    wl_resource_set_implementation(resource, &s_plasmaShellImpl, data, nullptr);
}

void VeridianPlasmaShellInterface::getShellSurface(
    struct wl_client *client, struct wl_resource *resource,
    uint32_t id, struct wl_resource *surface)
{
    auto *self = static_cast<VeridianPlasmaShellInterface *>(
        wl_resource_get_user_data(resource));

    auto *data = new PlasmaShellSurfaceData;
    memset(data, 0, sizeof(*data));
    data->surface = surface;

    struct wl_resource *shellSurface = wl_resource_create(client,
        &org_kde_plasma_surface_interface, wl_resource_get_version(resource), id);

    data->resource = shellSurface;
    wl_resource_set_implementation(shellSurface, &s_plasmaSurfaceImpl,
                                   data, shellSurfaceDestroy);

    self->m_surfaces.append(data);
    Q_EMIT self->surfaceCreated(data);
}

void VeridianPlasmaShellInterface::shellSurfaceSetRole(
    struct wl_client *, struct wl_resource *resource, uint32_t role)
{
    auto *data = static_cast<PlasmaShellSurfaceData *>(
        wl_resource_get_user_data(resource));
    data->role = role;
}

void VeridianPlasmaShellInterface::shellSurfaceSetPosition(
    struct wl_client *, struct wl_resource *resource, int32_t x, int32_t y)
{
    auto *data = static_cast<PlasmaShellSurfaceData *>(
        wl_resource_get_user_data(resource));
    data->x = x;
    data->y = y;
    data->positionSet = true;
}

void VeridianPlasmaShellInterface::shellSurfaceSetPanelBehavior(
    struct wl_client *, struct wl_resource *resource, uint32_t behavior)
{
    auto *data = static_cast<PlasmaShellSurfaceData *>(
        wl_resource_get_user_data(resource));
    data->panelBehavior = behavior;
}

void VeridianPlasmaShellInterface::shellSurfaceSetSkipTaskbar(
    struct wl_client *, struct wl_resource *resource, uint32_t skip)
{
    auto *data = static_cast<PlasmaShellSurfaceData *>(
        wl_resource_get_user_data(resource));
    data->skipTaskbar = (skip != 0);
}

void VeridianPlasmaShellInterface::shellSurfaceSetSkipSwitcher(
    struct wl_client *, struct wl_resource *resource, uint32_t skip)
{
    auto *data = static_cast<PlasmaShellSurfaceData *>(
        wl_resource_get_user_data(resource));
    data->skipSwitcher = (skip != 0);
}

void VeridianPlasmaShellInterface::shellSurfaceDestroy(struct wl_resource *resource)
{
    auto *data = static_cast<PlasmaShellSurfaceData *>(
        wl_resource_get_user_data(resource));
    /* Note: caller must remove from m_surfaces list via surfaceDestroyed signal */
    delete data;
}

QVector<PlasmaShellSurfaceData *> VeridianPlasmaShellInterface::surfaces() const
{
    return m_surfaces;
}

PlasmaShellSurfaceData *VeridianPlasmaShellInterface::surfaceForResource(
    struct wl_resource *resource) const
{
    for (PlasmaShellSurfaceData *s : m_surfaces) {
        if (s->surface == resource)
            return s;
    }
    return nullptr;
}

/* ========================================================================= */
/* VeridianWindowManagementInterface                                         */
/* ========================================================================= */

VeridianWindowManagementInterface::VeridianWindowManagementInterface(
    struct wl_display *display, QObject *parent)
    : QObject(parent)
    , m_display(display)
    , m_global(nullptr)
{
    m_global = wl_global_create(display,
        &org_kde_plasma_window_management_interface,
        16, this, bind);
    if (!m_global) {
        qWarning("VeridianWindowManagement: wl_global_create failed");
    }
}

VeridianWindowManagementInterface::~VeridianWindowManagementInterface()
{
    if (m_global)
        wl_global_destroy(m_global);
}

void VeridianWindowManagementInterface::bind(struct wl_client *client,
                                              void *data,
                                              uint32_t version, uint32_t id)
{
    auto *self = static_cast<VeridianWindowManagementInterface *>(data);

    struct wl_resource *resource = wl_resource_create(client,
        &org_kde_plasma_window_management_interface,
        static_cast<int>(qMin(version, 16u)), id);
    wl_resource_set_implementation(resource, nullptr, self, nullptr);

    self->m_boundResources.append(resource);

    /* Send existing windows to newly bound client */
    for (auto it = self->m_windows.begin(); it != self->m_windows.end(); ++it) {
        self->sendWindowToClient(resource, it.value());
    }
}

void VeridianWindowManagementInterface::sendWindowToClient(
    struct wl_resource *managerResource, const ManagedWindowData &window)
{
    /* Create a per-window resource for this client */
    struct wl_client *client = wl_resource_get_client(managerResource);
    struct wl_resource *windowResource = wl_resource_create(client,
        &org_kde_plasma_window_interface,
        wl_resource_get_version(managerResource), 0);

    /* Set up per-window callbacks */
    static const struct org_kde_plasma_window_interface s_windowImpl = {
        VeridianWindowManagementInterface::windowSetState,
        VeridianWindowManagementInterface::windowClose,
        VeridianWindowManagementInterface::windowRequestMove,
        VeridianWindowManagementInterface::windowRequestResize,
        VeridianWindowManagementInterface::windowRequestVirtualDesktop,
    };

    /* Store internal ID in user data for callback routing */
    uint32_t *idPtr = new uint32_t(window.internalId);
    wl_resource_set_implementation(windowResource, &s_windowImpl,
                                   idPtr, windowDestroy);

    /* Send the window announcement */
    org_kde_plasma_window_management_send_window(managerResource,
                                                  window.internalId);

    /* Send window properties */
    org_kde_plasma_window_send_title_changed(windowResource,
                                              window.title.toUtf8().constData());
    org_kde_plasma_window_send_app_id_changed(windowResource,
                                               window.appId.toUtf8().constData());
    org_kde_plasma_window_send_state_changed(windowResource, window.state);
    org_kde_plasma_window_send_pid_changed(windowResource, window.pid);

    if (window.geometry.isValid()) {
        org_kde_plasma_window_send_geometry(windowResource,
            window.geometry.x(), window.geometry.y(),
            window.geometry.width(), window.geometry.height());
    }

    /* Send virtual desktop membership */
    for (const QString &desktopId : window.virtualDesktopIds) {
        org_kde_plasma_window_send_virtual_desktop_entered(
            windowResource, desktopId.toUtf8().constData());
    }
}

void VeridianWindowManagementInterface::addWindow(uint32_t internalId,
                                                   const QString &title,
                                                   const QString &appId,
                                                   uint32_t pid)
{
    ManagedWindowData window;
    window.internalId = internalId;
    window.windowResource = nullptr;
    window.title = title;
    window.appId = appId;
    window.pid = pid;
    window.state = 0;
    window.closeable = true;
    window.movable = true;
    window.resizable = true;
    window.maximizable = true;
    window.minimizable = true;
    window.fullscreenable = true;

    m_windows.insert(internalId, window);

    /* Notify all bound clients */
    for (struct wl_resource *res : m_boundResources) {
        sendWindowToClient(res, window);
    }
}

void VeridianWindowManagementInterface::removeWindow(uint32_t internalId)
{
    m_windows.remove(internalId);
    /* Clients receive the unmapped event via the per-window resource destroy */
}

void VeridianWindowManagementInterface::updateWindowTitle(uint32_t internalId,
                                                          const QString &title)
{
    if (m_windows.contains(internalId)) {
        m_windows[internalId].title = title;
    }
}

void VeridianWindowManagementInterface::updateWindowState(uint32_t internalId,
                                                          uint32_t state)
{
    if (m_windows.contains(internalId)) {
        m_windows[internalId].state = state;
    }
}

void VeridianWindowManagementInterface::updateWindowGeometry(uint32_t internalId,
                                                              const QRect &geometry)
{
    if (m_windows.contains(internalId)) {
        m_windows[internalId].geometry = geometry;
    }
}

void VeridianWindowManagementInterface::updateWindowVirtualDesktop(
    uint32_t internalId, const QStringList &desktopIds)
{
    if (m_windows.contains(internalId)) {
        m_windows[internalId].virtualDesktopIds = desktopIds;
    }
}

void VeridianWindowManagementInterface::setShowDesktop(bool show)
{
    for (struct wl_resource *res : m_boundResources) {
        org_kde_plasma_window_management_send_show_desktop_changed(
            res, show ? 1 : 0);
    }
}

void VeridianWindowManagementInterface::updateStackingOrder(
    const QVector<uint32_t> &order)
{
    /* Create wl_array from stacking order */
    struct wl_array arr;
    wl_array_init(&arr);

    for (uint32_t id : order) {
        uint32_t *ptr = static_cast<uint32_t *>(wl_array_add(&arr, sizeof(uint32_t)));
        if (ptr)
            *ptr = id;
    }

    for (struct wl_resource *res : m_boundResources) {
        org_kde_plasma_window_management_send_stacking_order_changed(res, &arr);
    }

    wl_array_release(&arr);
}

void VeridianWindowManagementInterface::windowSetState(
    struct wl_client *, struct wl_resource *resource,
    uint32_t flags, uint32_t state)
{
    uint32_t *idPtr = static_cast<uint32_t *>(wl_resource_get_user_data(resource));
    if (!idPtr)
        return;

    /* Decode state change and emit appropriate signal.
     * Active bit = 0x001, Minimized = 0x002, Maximized = 0x004 */
    if (flags & 0x001) {
        /* Activate request */
        /* Signal handled by caller */
    }
    if (flags & 0x002) {
        /* Minimize/unminimize */
    }
    if (flags & 0x004) {
        /* Maximize/unmaximize */
    }

    Q_UNUSED(state);
}

void VeridianWindowManagementInterface::windowClose(
    struct wl_client *, struct wl_resource *resource)
{
    Q_UNUSED(resource);
    /* Signal close request to compositor */
}

void VeridianWindowManagementInterface::windowRequestMove(
    struct wl_client *, struct wl_resource *resource)
{
    Q_UNUSED(resource);
}

void VeridianWindowManagementInterface::windowRequestResize(
    struct wl_client *, struct wl_resource *resource)
{
    Q_UNUSED(resource);
}

void VeridianWindowManagementInterface::windowRequestVirtualDesktop(
    struct wl_client *, struct wl_resource *resource, const char *id)
{
    Q_UNUSED(resource);
    Q_UNUSED(id);
}

void VeridianWindowManagementInterface::windowDestroy(struct wl_resource *resource)
{
    uint32_t *idPtr = static_cast<uint32_t *>(wl_resource_get_user_data(resource));
    delete idPtr;
}

/* ========================================================================= */
/* VeridianServerDecorationManager                                           */
/* ========================================================================= */

static const struct org_kde_kwin_server_decoration_manager_interface
    s_serverDecorationManagerImpl = {
    VeridianServerDecorationManager::create,
};

static const struct org_kde_kwin_server_decoration_interface
    s_serverDecorationImpl = {
    VeridianServerDecorationManager::requestMode,
};

VeridianServerDecorationManager::VeridianServerDecorationManager(
    struct wl_display *display, QObject *parent)
    : QObject(parent)
    , m_display(display)
    , m_global(nullptr)
    , m_defaultMode(Server)
{
    m_global = wl_global_create(display,
        &org_kde_kwin_server_decoration_manager_interface,
        1, this, bind);
    if (!m_global) {
        qWarning("VeridianServerDecorationManager: wl_global_create failed");
    }
}

VeridianServerDecorationManager::~VeridianServerDecorationManager()
{
    if (m_global)
        wl_global_destroy(m_global);
}

void VeridianServerDecorationManager::bind(struct wl_client *client, void *data,
                                            uint32_t version, uint32_t id)
{
    auto *self = static_cast<VeridianServerDecorationManager *>(data);
    struct wl_resource *resource = wl_resource_create(client,
        &org_kde_kwin_server_decoration_manager_interface,
        static_cast<int>(qMin(version, 1u)), id);
    wl_resource_set_implementation(resource, &s_serverDecorationManagerImpl,
                                   self, nullptr);

    /* Send default decoration mode to client */
    org_kde_kwin_server_decoration_manager_send_default_mode(
        resource, static_cast<uint32_t>(self->m_defaultMode));
}

void VeridianServerDecorationManager::create(struct wl_client *client,
                                              struct wl_resource *resource,
                                              uint32_t id,
                                              struct wl_resource *surface)
{
    auto *self = static_cast<VeridianServerDecorationManager *>(
        wl_resource_get_user_data(resource));

    struct wl_resource *decoration = wl_resource_create(client,
        &org_kde_kwin_server_decoration_interface,
        wl_resource_get_version(resource), id);
    wl_resource_set_implementation(decoration, &s_serverDecorationImpl,
                                   self, decorationDestroy);

    /* Send current mode to client */
    org_kde_kwin_server_decoration_send_mode(
        decoration, static_cast<uint32_t>(self->m_defaultMode));

    Q_UNUSED(surface);
}

void VeridianServerDecorationManager::requestMode(struct wl_client *,
                                                    struct wl_resource *resource,
                                                    uint32_t mode)
{
    auto *self = static_cast<VeridianServerDecorationManager *>(
        wl_resource_get_user_data(resource));

    /* Accept the requested mode or enforce server-side */
    DecorationMode resultMode;
    if (mode == static_cast<uint32_t>(Client)) {
        /* Allow CSD if client requests it (e.g., GTK apps) */
        resultMode = Client;
    } else {
        /* Default to SSD for KDE apps */
        resultMode = self->m_defaultMode;
    }

    org_kde_kwin_server_decoration_send_mode(
        resource, static_cast<uint32_t>(resultMode));
}

void VeridianServerDecorationManager::decorationDestroy(struct wl_resource *)
{
    /* Nothing to clean up */
}

VeridianServerDecorationManager::DecorationMode
VeridianServerDecorationManager::defaultMode() const
{
    return m_defaultMode;
}

void VeridianServerDecorationManager::setDefaultMode(DecorationMode mode)
{
    m_defaultMode = mode;
}

/* ========================================================================= */
/* VeridianBlurManager                                                       */
/* ========================================================================= */

static const struct org_kde_kwin_blur_manager_interface s_blurManagerImpl = {
    VeridianBlurManager::createBlur,
    VeridianBlurManager::unsetBlur,
};

static const struct org_kde_kwin_blur_interface s_blurImpl = {
    VeridianBlurManager::blurCommit,
    VeridianBlurManager::blurSetRegion,
};

VeridianBlurManager::VeridianBlurManager(struct wl_display *display,
                                         bool gpuAccelerated,
                                         QObject *parent)
    : QObject(parent)
    , m_display(display)
    , m_global(nullptr)
    , m_enabled(gpuAccelerated)
    , m_gpuAccelerated(gpuAccelerated)
{
    m_global = wl_global_create(display, &org_kde_kwin_blur_manager_interface,
                                1, this, bind);
    if (!m_global) {
        qWarning("VeridianBlurManager: wl_global_create failed");
    }

    if (!gpuAccelerated) {
        qDebug("VeridianBlurManager: blur disabled (software rendering)");
    }
}

VeridianBlurManager::~VeridianBlurManager()
{
    qDeleteAll(m_blurs);
    if (m_global)
        wl_global_destroy(m_global);
}

void VeridianBlurManager::bind(struct wl_client *client, void *data,
                                uint32_t version, uint32_t id)
{
    struct wl_resource *resource = wl_resource_create(client,
        &org_kde_kwin_blur_manager_interface,
        static_cast<int>(qMin(version, 1u)), id);
    wl_resource_set_implementation(resource, &s_blurManagerImpl, data, nullptr);
}

void VeridianBlurManager::createBlur(struct wl_client *client,
                                      struct wl_resource *resource,
                                      uint32_t id,
                                      struct wl_resource *surface)
{
    auto *self = static_cast<VeridianBlurManager *>(
        wl_resource_get_user_data(resource));

    auto *data = new BlurRegionData;
    data->surface = surface;

    struct wl_resource *blurResource = wl_resource_create(client,
        &org_kde_kwin_blur_interface,
        wl_resource_get_version(resource), id);
    data->resource = blurResource;

    wl_resource_set_implementation(blurResource, &s_blurImpl, data, blurDestroy);

    self->m_blurs.append(data);

    if (self->m_enabled) {
        Q_EMIT self->blurCreated(data);
    }
}

void VeridianBlurManager::unsetBlur(struct wl_client *,
                                     struct wl_resource *resource,
                                     struct wl_resource *surface)
{
    auto *self = static_cast<VeridianBlurManager *>(
        wl_resource_get_user_data(resource));

    for (int i = 0; i < self->m_blurs.size(); ++i) {
        if (self->m_blurs[i]->surface == surface) {
            BlurRegionData *data = self->m_blurs.takeAt(i);
            Q_EMIT self->blurDestroyed(data);
            delete data;
            break;
        }
    }
}

void VeridianBlurManager::blurCommit(struct wl_client *,
                                      struct wl_resource *resource)
{
    Q_UNUSED(resource);
    /* Commit blur region to compositor for next frame */
}

void VeridianBlurManager::blurSetRegion(struct wl_client *,
                                         struct wl_resource *resource,
                                         struct wl_resource *region)
{
    Q_UNUSED(resource);
    Q_UNUSED(region);
    /* Parse wl_region and store as QVector<QRect> in BlurRegionData */
}

void VeridianBlurManager::blurDestroy(struct wl_resource *resource)
{
    auto *data = static_cast<BlurRegionData *>(
        wl_resource_get_user_data(resource));
    delete data;
}

bool VeridianBlurManager::isEnabled() const { return m_enabled; }

void VeridianBlurManager::setEnabled(bool enabled)
{
    m_enabled = enabled && m_gpuAccelerated;
}

QVector<BlurRegionData *> VeridianBlurManager::activeBlurs() const
{
    return m_blurs;
}

BlurRegionData *VeridianBlurManager::blurForSurface(
    struct wl_resource *surface) const
{
    for (BlurRegionData *b : m_blurs) {
        if (b->surface == surface)
            return b;
    }
    return nullptr;
}

/* ========================================================================= */
/* VeridianDpmsManager                                                       */
/* ========================================================================= */

static const struct org_kde_kwin_dpms_manager_interface s_dpmsManagerImpl = {
    VeridianDpmsManager::getDpms,
};

static const struct org_kde_kwin_dpms_interface s_dpmsImpl = {
    VeridianDpmsManager::setDpms,
};

VeridianDpmsManager::VeridianDpmsManager(struct wl_display *display,
                                         VeridianDrmBackend *backend,
                                         QObject *parent)
    : QObject(parent)
    , m_display(display)
    , m_global(nullptr)
    , m_backend(backend)
{
    m_global = wl_global_create(display, &org_kde_kwin_dpms_manager_interface,
                                1, this, bind);
    if (!m_global) {
        qWarning("VeridianDpmsManager: wl_global_create failed");
    }

    /* Initialize DPMS states for all outputs */
    if (backend) {
        for (VeridianDrmOutput *output : backend->outputs()) {
            m_dpmsStates.insert(output->connectorId(), 0); /* DRM_MODE_DPMS_ON */
        }
    }
}

VeridianDpmsManager::~VeridianDpmsManager()
{
    if (m_global)
        wl_global_destroy(m_global);
}

void VeridianDpmsManager::bind(struct wl_client *client, void *data,
                                uint32_t version, uint32_t id)
{
    struct wl_resource *resource = wl_resource_create(client,
        &org_kde_kwin_dpms_manager_interface,
        static_cast<int>(qMin(version, 1u)), id);
    wl_resource_set_implementation(resource, &s_dpmsManagerImpl, data, nullptr);
}

void VeridianDpmsManager::getDpms(struct wl_client *client,
                                   struct wl_resource *resource,
                                   uint32_t id, struct wl_resource *output)
{
    auto *self = static_cast<VeridianDpmsManager *>(
        wl_resource_get_user_data(resource));

    struct wl_resource *dpmsResource = wl_resource_create(client,
        &org_kde_kwin_dpms_interface,
        wl_resource_get_version(resource), id);
    wl_resource_set_implementation(dpmsResource, &s_dpmsImpl, self, dpmsDestroy);

    /* Send current DPMS state for this output.
     * We store the wl_output resource ID as a proxy for connector ID. */
    uint32_t connectorId = wl_resource_get_id(output);
    self->sendDpmsState(dpmsResource, connectorId);
}

void VeridianDpmsManager::setDpms(struct wl_client *,
                                   struct wl_resource *resource,
                                   uint32_t mode)
{
    auto *self = static_cast<VeridianDpmsManager *>(
        wl_resource_get_user_data(resource));

    /* Apply DPMS mode to all outputs (simplified -- a full implementation
     * would track which output this DPMS resource is bound to) */
    if (self->m_backend) {
        for (VeridianDrmOutput *output : self->m_backend->outputs()) {
            if (output->setDpms(static_cast<int>(mode))) {
                self->m_dpmsStates[output->connectorId()] = static_cast<int>(mode);
                Q_EMIT self->dpmsStateChanged(output->connectorId(),
                                               static_cast<int>(mode));
            }
        }
    }

    /* Confirm the mode change to the client */
    org_kde_kwin_dpms_send_mode(resource, mode);
    org_kde_kwin_dpms_send_done(resource);
}

void VeridianDpmsManager::dpmsDestroy(struct wl_resource *)
{
    /* Nothing to clean up */
}

void VeridianDpmsManager::sendDpmsState(struct wl_resource *resource,
                                         uint32_t connectorId)
{
    bool supported = true; /* DRM connectors generally support DPMS */
    int state = m_dpmsStates.value(connectorId, 0);

    org_kde_kwin_dpms_send_supported(resource, supported ? 1 : 0);
    org_kde_kwin_dpms_send_mode(resource, static_cast<uint32_t>(state));
    org_kde_kwin_dpms_send_done(resource);
}

int VeridianDpmsManager::dpmsState(uint32_t connectorId) const
{
    return m_dpmsStates.value(connectorId, 0);
}

bool VeridianDpmsManager::isSupported(uint32_t connectorId) const
{
    Q_UNUSED(connectorId);
    return true;
}

/* ========================================================================= */
/* VeridianOutputDeviceInterface                                             */
/* ========================================================================= */

VeridianOutputDeviceInterface::VeridianOutputDeviceInterface(
    struct wl_display *display, QObject *parent)
    : QObject(parent)
    , m_display(display)
    , m_global(nullptr)
{
    m_global = wl_global_create(display, &org_kde_kwin_outputdevice_interface,
                                2, this, bind);
    if (!m_global) {
        qWarning("VeridianOutputDevice: wl_global_create failed");
    }
}

VeridianOutputDeviceInterface::~VeridianOutputDeviceInterface()
{
    if (m_global)
        wl_global_destroy(m_global);
}

void VeridianOutputDeviceInterface::bind(struct wl_client *client, void *data,
                                          uint32_t version, uint32_t id)
{
    auto *self = static_cast<VeridianOutputDeviceInterface *>(data);

    struct wl_resource *resource = wl_resource_create(client,
        &org_kde_kwin_outputdevice_interface,
        static_cast<int>(qMin(version, 2u)), id);
    wl_resource_set_implementation(resource, nullptr, self, nullptr);

    self->m_boundResources.append(resource);

    /* Send all known outputs to the newly bound client */
    for (const OutputDeviceData &output : self->m_outputs) {
        self->sendOutputData(resource, output);
    }
}

void VeridianOutputDeviceInterface::sendOutputData(
    struct wl_resource *resource, const OutputDeviceData &data)
{
    org_kde_kwin_outputdevice_send_geometry(resource,
        data.globalPosition.x(), data.globalPosition.y(),
        data.physicalSize.width(), data.physicalSize.height(),
        0, /* subpixel: unknown */
        data.manufacturer.toUtf8().constData(),
        data.model.toUtf8().constData(),
        data.transform);

    /* Send modes */
    for (int i = 0; i < data.modes.size(); ++i) {
        bool current = (i == data.currentModeIndex);
        bool preferred = (i == data.preferredModeIndex);
        sendMode(resource, data.modes[i], i, current, preferred);
    }

    org_kde_kwin_outputdevice_send_scale(resource, data.scale);
    org_kde_kwin_outputdevice_send_enabled(resource, data.enabled ? 1 : 0);
    org_kde_kwin_outputdevice_send_serial_number(resource,
        data.serialNumber.toUtf8().constData());
    org_kde_kwin_outputdevice_send_done(resource);
}

void VeridianOutputDeviceInterface::sendMode(
    struct wl_resource *resource, const drmModeModeInfo &mode,
    int index, bool current, bool preferred)
{
    uint32_t flags = 0;
    if (current)
        flags |= 0x1;    /* WL_OUTPUT_MODE_CURRENT */
    if (preferred)
        flags |= 0x2;    /* WL_OUTPUT_MODE_PREFERRED */

    org_kde_kwin_outputdevice_send_mode(resource,
        flags, mode.hdisplay, mode.vdisplay,
        mode.vrefresh * 1000, index);
}

void VeridianOutputDeviceInterface::addOutput(const OutputDeviceData &data)
{
    m_outputs.append(data);
    for (struct wl_resource *res : m_boundResources) {
        sendOutputData(res, data);
    }
}

void VeridianOutputDeviceInterface::removeOutput(uint32_t id)
{
    for (int i = 0; i < m_outputs.size(); ++i) {
        if (m_outputs[i].id == id) {
            m_outputs.removeAt(i);
            break;
        }
    }
}

void VeridianOutputDeviceInterface::updateOutput(const OutputDeviceData &data)
{
    for (int i = 0; i < m_outputs.size(); ++i) {
        if (m_outputs[i].id == data.id) {
            m_outputs[i] = data;
            for (struct wl_resource *res : m_boundResources) {
                sendOutputData(res, data);
            }
            break;
        }
    }
}

QVector<OutputDeviceData> VeridianOutputDeviceInterface::outputs() const
{
    return m_outputs;
}

/* ========================================================================= */
/* VeridianOutputManagement                                                  */
/* ========================================================================= */

VeridianOutputManagement::VeridianOutputManagement(
    struct wl_display *display, VeridianDrmBackend *backend, QObject *parent)
    : QObject(parent)
    , m_display(display)
    , m_global(nullptr)
    , m_backend(backend)
{
    m_global = wl_global_create(display,
        &org_kde_kwin_outputmanagement_interface,
        2, this, bind);
    if (!m_global) {
        qWarning("VeridianOutputManagement: wl_global_create failed");
    }
}

VeridianOutputManagement::~VeridianOutputManagement()
{
    if (m_global)
        wl_global_destroy(m_global);
}

static const struct org_kde_kwin_outputmanagement_interface
    s_outputManagementImpl = {
    VeridianOutputManagement::createConfiguration,
};

void VeridianOutputManagement::bind(struct wl_client *client, void *data,
                                     uint32_t version, uint32_t id)
{
    struct wl_resource *resource = wl_resource_create(client,
        &org_kde_kwin_outputmanagement_interface,
        static_cast<int>(qMin(version, 2u)), id);
    wl_resource_set_implementation(resource, &s_outputManagementImpl,
                                   data, nullptr);
}

void VeridianOutputManagement::createConfiguration(struct wl_client *client,
                                                    struct wl_resource *resource,
                                                    uint32_t id)
{
    auto *self = static_cast<VeridianOutputManagement *>(
        wl_resource_get_user_data(resource));

    static const struct org_kde_kwin_outputconfiguration_interface s_configImpl = {
        VeridianOutputManagement::configEnable,
        VeridianOutputManagement::configMode,
        VeridianOutputManagement::configTransform,
        VeridianOutputManagement::configScale,
        VeridianOutputManagement::configPosition,
        VeridianOutputManagement::configApply,
    };

    struct wl_resource *configResource = wl_resource_create(client,
        &org_kde_kwin_outputconfiguration_interface,
        wl_resource_get_version(resource), id);
    wl_resource_set_implementation(configResource, &s_configImpl,
                                   self, configDestroy);
}

void VeridianOutputManagement::configEnable(
    struct wl_client *, struct wl_resource *, struct wl_resource *, int32_t)
{
    /* Store enable/disable in pending configuration */
}

void VeridianOutputManagement::configMode(
    struct wl_client *, struct wl_resource *, struct wl_resource *, int32_t)
{
    /* Store mode index in pending configuration */
}

void VeridianOutputManagement::configTransform(
    struct wl_client *, struct wl_resource *, struct wl_resource *, int32_t)
{
    /* Store transform in pending configuration */
}

void VeridianOutputManagement::configScale(
    struct wl_client *, struct wl_resource *, struct wl_resource *, int32_t)
{
    /* Store scale in pending configuration */
}

void VeridianOutputManagement::configPosition(
    struct wl_client *, struct wl_resource *, struct wl_resource *,
    int32_t, int32_t)
{
    /* Store position in pending configuration */
}

void VeridianOutputManagement::configApply(struct wl_client *,
                                            struct wl_resource *resource)
{
    /* Apply all pending configuration changes via DRM/KMS.
     * Send applied/failed event back to client. */
    org_kde_kwin_outputconfiguration_send_applied(resource);
}

void VeridianOutputManagement::configDestroy(struct wl_resource *)
{
    /* Clean up pending configuration */
}

bool VeridianOutputManagement::applyConfiguration(
    const QVector<OutputConfigChange> &changes)
{
    if (!m_backend)
        return false;

    for (const OutputConfigChange &change : changes) {
        /* Find the output for this change */
        for (VeridianDrmOutput *output : m_backend->outputs()) {
            if (output->connectorId() == change.outputId) {
                if (change.modeIndex >= 0) {
                    QVector<drmModeModeInfo> modes = output->availableModes();
                    if (change.modeIndex < modes.size()) {
                        output->setMode(modes[change.modeIndex]);
                    }
                }
                /* Additional changes (transform, scale, position) would
                 * be applied here in a full implementation */
                break;
            }
        }
    }

    Q_EMIT configurationChangeRequested(changes);
    return true;
}

/* ========================================================================= */
/* VeridianProtocolRegistry                                                  */
/* ========================================================================= */

VeridianProtocolRegistry::VeridianProtocolRegistry(
    struct wl_display *display, VeridianDrmBackend *backend, QObject *parent)
    : QObject(parent)
    , m_display(display)
    , m_backend(backend)
    , m_plasmaShell(nullptr)
    , m_windowManagement(nullptr)
    , m_serverDecoration(nullptr)
    , m_blurManager(nullptr)
    , m_dpmsManager(nullptr)
    , m_outputDevice(nullptr)
    , m_outputManagement(nullptr)
{
}

VeridianProtocolRegistry::~VeridianProtocolRegistry()
{
    delete m_outputManagement;
    delete m_outputDevice;
    delete m_dpmsManager;
    delete m_blurManager;
    delete m_serverDecoration;
    delete m_windowManagement;
    delete m_plasmaShell;
}

bool VeridianProtocolRegistry::initialize()
{
    bool gpuAccelerated = true;
    if (m_backend && m_backend->eglBackend()) {
        gpuAccelerated = !m_backend->eglBackend()->isLlvmpipe();
    }

    m_plasmaShell = new VeridianPlasmaShellInterface(m_display, this);
    m_windowManagement = new VeridianWindowManagementInterface(m_display, this);
    m_serverDecoration = new VeridianServerDecorationManager(m_display, this);
    m_blurManager = new VeridianBlurManager(m_display, gpuAccelerated, this);
    m_dpmsManager = new VeridianDpmsManager(m_display, m_backend, this);
    m_outputDevice = new VeridianOutputDeviceInterface(m_display, this);
    m_outputManagement = new VeridianOutputManagement(m_display, m_backend, this);

    /* Register outputs from DRM backend into output device protocol */
    if (m_backend) {
        for (VeridianDrmOutput *output : m_backend->outputs()) {
            OutputDeviceData data;
            data.id = output->connectorId();
            data.manufacturer = QStringLiteral("VeridianOS");
            data.model = output->name();
            data.serialNumber = QStringLiteral("VIRT-001");
            data.physicalSize = output->sizeMillimeters();
            data.globalPosition = QPoint(0, 0);
            data.currentModeIndex = 0;
            data.preferredModeIndex = 0;
            data.transform = 0;
            data.scale = 1000;  /* 1.0x in fixed-point */
            data.enabled = true;
            data.connectorId = output->connectorId();

            /* Copy modes from DRM output */
            data.modes = output->availableModes();

            m_outputDevice->addOutput(data);
        }
    }

    qDebug("VeridianProtocolRegistry: all KDE Wayland protocols registered "
           "(blur %s)", gpuAccelerated ? "enabled" : "disabled");

    return true;
}

VeridianPlasmaShellInterface *VeridianProtocolRegistry::plasmaShell() const
{
    return m_plasmaShell;
}

VeridianWindowManagementInterface *VeridianProtocolRegistry::windowManagement() const
{
    return m_windowManagement;
}

VeridianServerDecorationManager *VeridianProtocolRegistry::serverDecorationManager() const
{
    return m_serverDecoration;
}

VeridianBlurManager *VeridianProtocolRegistry::blurManager() const
{
    return m_blurManager;
}

VeridianDpmsManager *VeridianProtocolRegistry::dpmsManager() const
{
    return m_dpmsManager;
}

VeridianOutputDeviceInterface *VeridianProtocolRegistry::outputDevice() const
{
    return m_outputDevice;
}

VeridianOutputManagement *VeridianProtocolRegistry::outputManagement() const
{
    return m_outputManagement;
}

} /* namespace KWin */
