//! System call numbers (243 calls; ADR 0009).
//!
//! Generated by tools/compat/gen_syscalls.py from abi/syscalls.map and
//! abi/linux/syscall_64.tbl. Do not edit; edit the map and regenerate.
//!
//! A call that Linux also has uses its Linux x86_64 number; a call only
//! VeridianOS has uses a private number from 1024 up.

/// System call numbers
#[repr(usize)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Syscall {
    // VeridianOS IPC
    /// VeridianOS only
    IpcSend = 1024,
    /// VeridianOS only
    IpcReceive = 1025,
    /// VeridianOS only
    IpcCall = 1026,
    /// VeridianOS only
    IpcReply = 1027,
    /// VeridianOS only
    IpcCreateEndpoint = 1028,
    /// VeridianOS only
    IpcBindEndpoint = 1029,
    /// VeridianOS only
    IpcShareMemory = 1030,
    /// VeridianOS only
    IpcMapMemory = 1031,

    // Process management
    /// Linux `sched_yield`
    SchedYield = 24,
    /// Linux `exit_group`
    ExitGroup = 231,
    /// Linux `fork`
    Fork = 57,
    /// Linux `vfork`
    Vfork = 58,
    /// Linux `execve`
    Execve = 59,
    /// Linux `wait4`
    Wait4 = 61,
    /// Linux `getpid`
    Getpid = 39,
    /// Linux `getppid`
    Getppid = 110,
    /// VeridianOS only
    ProcessSetPriority = 1041,
    /// VeridianOS only
    ProcessGetPriority = 1042,
    /// Linux `getcwd`
    Getcwd = 79,
    /// Linux `chdir`
    Chdir = 80,
    /// Linux `fchdir`
    Fchdir = 81,
    /// Linux `chroot`
    Chroot = 161,
    /// Linux `kill`
    Kill = 62,
    /// Linux `umask`
    Umask = 95,
    /// Linux `uname`
    Uname = 63,
    /// VeridianOS only
    ProcessGetenv = 1229,
    /// Linux `waitid`
    Waitid = 247,
    /// Linux `prctl`
    Prctl = 157,
    /// Linux `ptrace`
    Ptrace = 101,

    // Memory
    /// Linux `mmap`
    Mmap = 9,
    /// Linux `munmap`
    Munmap = 11,
    /// Linux `mprotect`
    Mprotect = 10,
    /// Linux `brk`
    Brk = 12,
    /// Linux `madvise`
    Madvise = 28,
    /// Linux `mremap`
    Mremap = 25,
    /// Linux `memfd_create`
    MemfdCreate = 319,

    // Capabilities
    /// VeridianOS only
    CapabilityGrant = 1054,
    /// VeridianOS only
    CapabilityRevoke = 1055,

    // Threads
    /// VeridianOS only
    ThreadCreate = 1064,
    /// Linux `exit`
    Exit = 60,
    /// VeridianOS only
    ThreadJoin = 1066,
    /// Linux `gettid`
    Gettid = 186,
    /// VeridianOS only
    ThreadSetAffinity = 1068,
    /// VeridianOS only
    ThreadGetAffinity = 1069,
    /// Linux `clone`
    Clone = 56,
    /// Linux `clone3`
    Clone3 = 435,
    /// Linux `set_tid_address`
    SetTidAddress = 218,
    /// Linux `set_robust_list`
    SetRobustList = 273,
    /// Linux `get_robust_list`
    GetRobustList = 274,
    /// Linux `rseq`
    Rseq = 334,
    /// Linux `arch_prctl`
    ArchPrctl = 158,
    /// Linux `tkill`
    Tkill = 200,
    /// Linux `tgkill`
    Tgkill = 234,

    // Files
    /// Linux `open`
    Open = 2,
    /// Linux `openat`
    Openat = 257,
    /// Linux `close`
    Close = 3,
    /// Linux `read`
    Read = 0,
    /// Linux `write`
    Write = 1,
    /// Linux `lseek`
    Lseek = 8,
    /// Linux `pread64`
    Pread64 = 17,
    /// Linux `pwrite64`
    Pwrite64 = 18,
    /// Linux `readv`
    Readv = 19,
    /// Linux `writev`
    Writev = 20,
    /// Linux `fstat`
    Fstat = 5,
    /// Linux `stat`
    Stat = 4,
    /// Linux `lstat`
    Lstat = 6,
    /// Linux `newfstatat`
    Newfstatat = 262,
    /// Linux `statx`
    Statx = 332,
    /// Linux `statfs`
    Statfs = 137,
    /// Linux `fstatfs`
    Fstatfs = 138,
    /// Linux `ftruncate`
    Ftruncate = 77,
    /// Linux `truncate`
    Truncate = 76,
    /// Linux `fallocate`
    Fallocate = 285,
    /// Linux `dup`
    Dup = 32,
    /// Linux `dup2`
    Dup2 = 33,
    /// Linux `dup3`
    Dup3 = 292,
    /// Linux `pipe`
    Pipe = 22,
    /// Linux `pipe2`
    Pipe2 = 293,
    /// Linux `ioctl`
    Ioctl = 16,
    /// Linux `fcntl`
    Fcntl = 72,
    /// Linux `flock`
    Flock = 73,
    /// Linux `access`
    Access = 21,
    /// Linux `faccessat`
    Faccessat = 269,
    /// Linux `faccessat2`
    Faccessat2 = 439,
    /// Linux `chmod`
    Chmod = 90,
    /// Linux `fchmod`
    Fchmod = 91,
    /// Linux `fchmodat`
    Fchmodat = 268,
    /// Linux `chown`
    Chown = 92,
    /// Linux `fchown`
    Fchown = 93,
    /// Linux `fchownat`
    Fchownat = 260,
    /// Linux `mknod`
    Mknod = 133,
    /// Linux `rename`
    Rename = 82,
    /// Linux `renameat`
    Renameat = 264,
    /// Linux `link`
    Link = 86,
    /// Linux `linkat`
    Linkat = 265,
    /// Linux `symlink`
    Symlink = 88,
    /// Linux `symlinkat`
    Symlinkat = 266,
    /// Linux `readlink`
    Readlink = 89,
    /// Linux `readlinkat`
    Readlinkat = 267,
    /// Linux `utimensat`
    Utimensat = 280,
    /// Linux `unlink`
    Unlink = 87,
    /// Linux `unlinkat`
    Unlinkat = 263,
    /// Linux `poll`
    Poll = 7,
    /// Linux `ppoll`
    Ppoll = 271,
    /// Linux `select`
    Select = 23,
    /// Linux `pselect6`
    Pselect6 = 270,
    /// Linux `getdents64`
    Getdents64 = 217,

    // Directories
    /// Linux `mkdir`
    Mkdir = 83,
    /// Linux `mkdirat`
    Mkdirat = 258,
    /// Linux `rmdir`
    Rmdir = 84,
    /// VeridianOS only
    DirOpendir = 1086,
    /// VeridianOS only
    DirReaddir = 1087,
    /// VeridianOS only
    DirClosedir = 1088,

    // Filesystems
    /// VeridianOS only
    FsMount = 1094,
    /// VeridianOS only
    FsUnmount = 1095,
    /// Linux `sync`
    Sync = 162,
    /// Linux `fsync`
    Fsync = 74,
    /// Linux `fdatasync`
    Fdatasync = 75,

    // Kernel information
    /// VeridianOS only
    KernelGetInfo = 1104,
    /// Linux `sysinfo`
    Sysinfo = 99,
    /// Linux `getrusage`
    Getrusage = 98,

    // Packages
    /// VeridianOS only
    PkgInstall = 1114,
    /// VeridianOS only
    PkgRemove = 1115,
    /// VeridianOS only
    PkgQuery = 1116,
    /// VeridianOS only
    PkgList = 1117,
    /// VeridianOS only
    PkgUpdate = 1118,

    // Time
    /// VeridianOS only
    TimeGetUptime = 1124,
    /// VeridianOS only
    TimeCreateTimer = 1125,
    /// VeridianOS only
    TimeCancelTimer = 1126,
    /// Linux `clock_gettime`
    ClockGettime = 228,
    /// Linux `clock_getres`
    ClockGetres = 229,
    /// Linux `clock_nanosleep`
    ClockNanosleep = 230,
    /// Linux `nanosleep`
    Nanosleep = 35,
    /// Linux `gettimeofday`
    Gettimeofday = 96,

    // Signals
    /// Linux `rt_sigaction`
    RtSigaction = 13,
    /// Linux `rt_sigprocmask`
    RtSigprocmask = 14,
    /// Linux `rt_sigsuspend`
    RtSigsuspend = 130,
    /// Linux `rt_sigreturn`
    RtSigreturn = 15,
    /// Linux `rt_sigpending`
    RtSigpending = 127,
    /// Linux `sigaltstack`
    Sigaltstack = 131,

    // Identity
    /// Linux `getuid`
    Getuid = 102,
    /// Linux `geteuid`
    Geteuid = 107,
    /// Linux `getgid`
    Getgid = 104,
    /// Linux `getegid`
    Getegid = 108,
    /// Linux `setuid`
    Setuid = 105,
    /// Linux `setgid`
    Setgid = 106,
    /// Linux `setreuid`
    Setreuid = 113,
    /// Linux `setregid`
    Setregid = 114,
    /// Linux `setresuid`
    Setresuid = 117,
    /// Linux `getresuid`
    Getresuid = 118,
    /// Linux `setresgid`
    Setresgid = 119,
    /// Linux `getresgid`
    Getresgid = 120,
    /// Linux `getgroups`
    Getgroups = 115,
    /// Linux `setgroups`
    Setgroups = 116,

    // Process groups and sessions
    /// Linux `setpgid`
    Setpgid = 109,
    /// Linux `getpgid`
    Getpgid = 121,
    /// Linux `getpgrp`
    Getpgrp = 111,
    /// Linux `setsid`
    Setsid = 112,
    /// Linux `getsid`
    Getsid = 124,
    /// VeridianOS only
    TcSetPgrp = 1298,
    /// VeridianOS only
    TcGetPgrp = 1299,

    // Scheduling
    /// Linux `sched_setscheduler`
    SchedSetscheduler = 144,
    /// Linux `sched_getscheduler`
    SchedGetscheduler = 145,
    /// Linux `sched_setparam`
    SchedSetparam = 142,
    /// Linux `sched_getparam`
    SchedGetparam = 143,
    /// Linux `sched_setattr`
    SchedSetattr = 314,
    /// Linux `sched_getattr`
    SchedGetattr = 315,
    /// Linux `sched_get_priority_max`
    SchedGetPriorityMax = 146,
    /// Linux `sched_get_priority_min`
    SchedGetPriorityMin = 147,
    /// Linux `sched_rr_get_interval`
    SchedRrGetInterval = 148,
    /// Linux `sched_setaffinity`
    SchedSetaffinity = 203,
    /// Linux `sched_getaffinity`
    SchedGetaffinity = 204,
    /// Linux `getpriority`
    Getpriority = 140,
    /// Linux `setpriority`
    Setpriority = 141,

    // Futexes
    /// Linux `futex`
    Futex = 202,
    /// VeridianOS only
    FutexWait = 1225,
    /// VeridianOS only
    FutexWake = 1226,

    // Shared memory
    /// VeridianOS only
    ShmOpen = 1234,
    /// VeridianOS only
    ShmUnlink = 1235,
    /// VeridianOS only
    ShmTruncate = 1236,

    // Sockets
    /// Linux `socket`
    Socket = 41,
    /// Linux `bind`
    Bind = 49,
    /// Linux `listen`
    Listen = 50,
    /// Linux `connect`
    Connect = 42,
    /// Linux `accept`
    Accept = 43,
    /// Linux `accept4`
    Accept4 = 288,
    /// VeridianOS only
    SocketSend = 1249,
    /// VeridianOS only
    SocketRecv = 1250,
    /// VeridianOS only
    SocketClose = 1251,
    /// Linux `socketpair`
    Socketpair = 53,
    /// Linux `sendto`
    Sendto = 44,
    /// Linux `recvfrom`
    Recvfrom = 45,
    /// Linux `getsockname`
    Getsockname = 51,
    /// Linux `getpeername`
    Getpeername = 52,
    /// Linux `setsockopt`
    Setsockopt = 54,
    /// Linux `getsockopt`
    Getsockopt = 55,
    /// Linux `sendmsg`
    Sendmsg = 46,
    /// Linux `recvmsg`
    Recvmsg = 47,

    // Framebuffer and input
    /// VeridianOS only
    FbGetInfo = 1254,
    /// VeridianOS only
    FbMap = 1255,
    /// VeridianOS only
    InputPoll = 1256,
    /// VeridianOS only
    InputRead = 1257,
    /// VeridianOS only
    FbSwap = 1258,

    // Wayland
    /// VeridianOS only
    WlConnect = 1264,
    /// VeridianOS only
    WlDisconnect = 1265,
    /// VeridianOS only
    WlSendMessage = 1266,
    /// VeridianOS only
    WlRecvMessage = 1267,
    /// VeridianOS only
    WlCreateShmPool = 1268,
    /// VeridianOS only
    WlCreateSurface = 1269,
    /// VeridianOS only
    WlCommitSurface = 1270,
    /// VeridianOS only
    WlGetEvents = 1271,

    // Resource limits
    /// Linux `getrlimit`
    Getrlimit = 97,
    /// Linux `setrlimit`
    Setrlimit = 160,
    /// Linux `prlimit64`
    Prlimit64 = 302,

    // epoll
    /// Linux `epoll_create`
    EpollCreate = 213,
    /// Linux `epoll_create1`
    EpollCreate1 = 291,
    /// Linux `epoll_ctl`
    EpollCtl = 233,
    /// Linux `epoll_wait`
    EpollWait = 232,
    /// Linux `epoll_pwait`
    EpollPwait = 281,
    /// Linux `epoll_pwait2`
    EpollPwait2 = 441,

    // Pseudo-terminals
    /// VeridianOS only
    OpenPty = 1304,
    /// VeridianOS only
    GrantPty = 1305,
    /// VeridianOS only
    UnlockPty = 1306,
    /// VeridianOS only
    PtsName = 1307,

    // Audio
    /// VeridianOS only
    AudioOpen = 1344,
    /// VeridianOS only
    AudioClose = 1345,
    /// VeridianOS only
    AudioWrite = 1346,
    /// VeridianOS only
    AudioSetVolume = 1347,
    /// VeridianOS only
    AudioGetInfo = 1348,
    /// VeridianOS only
    AudioStart = 1349,
    /// VeridianOS only
    AudioStop = 1350,
    /// VeridianOS only
    AudioPause = 1351,

    // Event, timer and signal descriptors
    /// Linux `getrandom`
    Getrandom = 318,
    /// Linux `eventfd`
    Eventfd = 284,
    /// Linux `eventfd2`
    Eventfd2 = 290,
    /// Linux `timerfd_create`
    TimerfdCreate = 283,
    /// Linux `timerfd_settime`
    TimerfdSettime = 286,
    /// Linux `timerfd_gettime`
    TimerfdGettime = 287,
    /// Linux `signalfd`
    Signalfd = 282,
    /// Linux `signalfd4`
    Signalfd4 = 289,

    // inotify
    /// Linux `inotify_init1`
    InotifyInit1 = 294,
    /// Linux `inotify_add_watch`
    InotifyAddWatch = 254,
    /// Linux `inotify_rm_watch`
    InotifyRmWatch = 255,
}

impl TryFrom<usize> for Syscall {
    type Error = ();

    fn try_from(value: usize) -> Result<Self, Self::Error> {
        match value {
            0 => Ok(Syscall::Read),
            1 => Ok(Syscall::Write),
            2 => Ok(Syscall::Open),
            3 => Ok(Syscall::Close),
            4 => Ok(Syscall::Stat),
            5 => Ok(Syscall::Fstat),
            6 => Ok(Syscall::Lstat),
            7 => Ok(Syscall::Poll),
            8 => Ok(Syscall::Lseek),
            9 => Ok(Syscall::Mmap),
            10 => Ok(Syscall::Mprotect),
            11 => Ok(Syscall::Munmap),
            12 => Ok(Syscall::Brk),
            13 => Ok(Syscall::RtSigaction),
            14 => Ok(Syscall::RtSigprocmask),
            15 => Ok(Syscall::RtSigreturn),
            16 => Ok(Syscall::Ioctl),
            17 => Ok(Syscall::Pread64),
            18 => Ok(Syscall::Pwrite64),
            19 => Ok(Syscall::Readv),
            20 => Ok(Syscall::Writev),
            21 => Ok(Syscall::Access),
            22 => Ok(Syscall::Pipe),
            23 => Ok(Syscall::Select),
            24 => Ok(Syscall::SchedYield),
            25 => Ok(Syscall::Mremap),
            28 => Ok(Syscall::Madvise),
            32 => Ok(Syscall::Dup),
            33 => Ok(Syscall::Dup2),
            35 => Ok(Syscall::Nanosleep),
            39 => Ok(Syscall::Getpid),
            41 => Ok(Syscall::Socket),
            42 => Ok(Syscall::Connect),
            43 => Ok(Syscall::Accept),
            44 => Ok(Syscall::Sendto),
            45 => Ok(Syscall::Recvfrom),
            46 => Ok(Syscall::Sendmsg),
            47 => Ok(Syscall::Recvmsg),
            49 => Ok(Syscall::Bind),
            50 => Ok(Syscall::Listen),
            51 => Ok(Syscall::Getsockname),
            52 => Ok(Syscall::Getpeername),
            53 => Ok(Syscall::Socketpair),
            54 => Ok(Syscall::Setsockopt),
            55 => Ok(Syscall::Getsockopt),
            56 => Ok(Syscall::Clone),
            57 => Ok(Syscall::Fork),
            58 => Ok(Syscall::Vfork),
            59 => Ok(Syscall::Execve),
            60 => Ok(Syscall::Exit),
            61 => Ok(Syscall::Wait4),
            62 => Ok(Syscall::Kill),
            63 => Ok(Syscall::Uname),
            72 => Ok(Syscall::Fcntl),
            73 => Ok(Syscall::Flock),
            74 => Ok(Syscall::Fsync),
            75 => Ok(Syscall::Fdatasync),
            76 => Ok(Syscall::Truncate),
            77 => Ok(Syscall::Ftruncate),
            79 => Ok(Syscall::Getcwd),
            80 => Ok(Syscall::Chdir),
            81 => Ok(Syscall::Fchdir),
            82 => Ok(Syscall::Rename),
            83 => Ok(Syscall::Mkdir),
            84 => Ok(Syscall::Rmdir),
            86 => Ok(Syscall::Link),
            87 => Ok(Syscall::Unlink),
            88 => Ok(Syscall::Symlink),
            89 => Ok(Syscall::Readlink),
            90 => Ok(Syscall::Chmod),
            91 => Ok(Syscall::Fchmod),
            92 => Ok(Syscall::Chown),
            93 => Ok(Syscall::Fchown),
            95 => Ok(Syscall::Umask),
            96 => Ok(Syscall::Gettimeofday),
            97 => Ok(Syscall::Getrlimit),
            98 => Ok(Syscall::Getrusage),
            99 => Ok(Syscall::Sysinfo),
            101 => Ok(Syscall::Ptrace),
            102 => Ok(Syscall::Getuid),
            104 => Ok(Syscall::Getgid),
            105 => Ok(Syscall::Setuid),
            106 => Ok(Syscall::Setgid),
            107 => Ok(Syscall::Geteuid),
            108 => Ok(Syscall::Getegid),
            109 => Ok(Syscall::Setpgid),
            110 => Ok(Syscall::Getppid),
            111 => Ok(Syscall::Getpgrp),
            112 => Ok(Syscall::Setsid),
            113 => Ok(Syscall::Setreuid),
            114 => Ok(Syscall::Setregid),
            115 => Ok(Syscall::Getgroups),
            116 => Ok(Syscall::Setgroups),
            117 => Ok(Syscall::Setresuid),
            118 => Ok(Syscall::Getresuid),
            119 => Ok(Syscall::Setresgid),
            120 => Ok(Syscall::Getresgid),
            121 => Ok(Syscall::Getpgid),
            124 => Ok(Syscall::Getsid),
            127 => Ok(Syscall::RtSigpending),
            130 => Ok(Syscall::RtSigsuspend),
            131 => Ok(Syscall::Sigaltstack),
            133 => Ok(Syscall::Mknod),
            137 => Ok(Syscall::Statfs),
            138 => Ok(Syscall::Fstatfs),
            140 => Ok(Syscall::Getpriority),
            141 => Ok(Syscall::Setpriority),
            142 => Ok(Syscall::SchedSetparam),
            143 => Ok(Syscall::SchedGetparam),
            144 => Ok(Syscall::SchedSetscheduler),
            145 => Ok(Syscall::SchedGetscheduler),
            146 => Ok(Syscall::SchedGetPriorityMax),
            147 => Ok(Syscall::SchedGetPriorityMin),
            148 => Ok(Syscall::SchedRrGetInterval),
            157 => Ok(Syscall::Prctl),
            158 => Ok(Syscall::ArchPrctl),
            160 => Ok(Syscall::Setrlimit),
            161 => Ok(Syscall::Chroot),
            162 => Ok(Syscall::Sync),
            186 => Ok(Syscall::Gettid),
            200 => Ok(Syscall::Tkill),
            202 => Ok(Syscall::Futex),
            203 => Ok(Syscall::SchedSetaffinity),
            204 => Ok(Syscall::SchedGetaffinity),
            213 => Ok(Syscall::EpollCreate),
            217 => Ok(Syscall::Getdents64),
            218 => Ok(Syscall::SetTidAddress),
            228 => Ok(Syscall::ClockGettime),
            229 => Ok(Syscall::ClockGetres),
            230 => Ok(Syscall::ClockNanosleep),
            231 => Ok(Syscall::ExitGroup),
            232 => Ok(Syscall::EpollWait),
            233 => Ok(Syscall::EpollCtl),
            234 => Ok(Syscall::Tgkill),
            247 => Ok(Syscall::Waitid),
            254 => Ok(Syscall::InotifyAddWatch),
            255 => Ok(Syscall::InotifyRmWatch),
            257 => Ok(Syscall::Openat),
            258 => Ok(Syscall::Mkdirat),
            260 => Ok(Syscall::Fchownat),
            262 => Ok(Syscall::Newfstatat),
            263 => Ok(Syscall::Unlinkat),
            264 => Ok(Syscall::Renameat),
            265 => Ok(Syscall::Linkat),
            266 => Ok(Syscall::Symlinkat),
            267 => Ok(Syscall::Readlinkat),
            268 => Ok(Syscall::Fchmodat),
            269 => Ok(Syscall::Faccessat),
            270 => Ok(Syscall::Pselect6),
            271 => Ok(Syscall::Ppoll),
            273 => Ok(Syscall::SetRobustList),
            274 => Ok(Syscall::GetRobustList),
            280 => Ok(Syscall::Utimensat),
            281 => Ok(Syscall::EpollPwait),
            282 => Ok(Syscall::Signalfd),
            283 => Ok(Syscall::TimerfdCreate),
            284 => Ok(Syscall::Eventfd),
            285 => Ok(Syscall::Fallocate),
            286 => Ok(Syscall::TimerfdSettime),
            287 => Ok(Syscall::TimerfdGettime),
            288 => Ok(Syscall::Accept4),
            289 => Ok(Syscall::Signalfd4),
            290 => Ok(Syscall::Eventfd2),
            291 => Ok(Syscall::EpollCreate1),
            292 => Ok(Syscall::Dup3),
            293 => Ok(Syscall::Pipe2),
            294 => Ok(Syscall::InotifyInit1),
            302 => Ok(Syscall::Prlimit64),
            314 => Ok(Syscall::SchedSetattr),
            315 => Ok(Syscall::SchedGetattr),
            318 => Ok(Syscall::Getrandom),
            319 => Ok(Syscall::MemfdCreate),
            332 => Ok(Syscall::Statx),
            334 => Ok(Syscall::Rseq),
            435 => Ok(Syscall::Clone3),
            439 => Ok(Syscall::Faccessat2),
            441 => Ok(Syscall::EpollPwait2),
            1024 => Ok(Syscall::IpcSend),
            1025 => Ok(Syscall::IpcReceive),
            1026 => Ok(Syscall::IpcCall),
            1027 => Ok(Syscall::IpcReply),
            1028 => Ok(Syscall::IpcCreateEndpoint),
            1029 => Ok(Syscall::IpcBindEndpoint),
            1030 => Ok(Syscall::IpcShareMemory),
            1031 => Ok(Syscall::IpcMapMemory),
            1041 => Ok(Syscall::ProcessSetPriority),
            1042 => Ok(Syscall::ProcessGetPriority),
            1054 => Ok(Syscall::CapabilityGrant),
            1055 => Ok(Syscall::CapabilityRevoke),
            1064 => Ok(Syscall::ThreadCreate),
            1066 => Ok(Syscall::ThreadJoin),
            1068 => Ok(Syscall::ThreadSetAffinity),
            1069 => Ok(Syscall::ThreadGetAffinity),
            1086 => Ok(Syscall::DirOpendir),
            1087 => Ok(Syscall::DirReaddir),
            1088 => Ok(Syscall::DirClosedir),
            1094 => Ok(Syscall::FsMount),
            1095 => Ok(Syscall::FsUnmount),
            1104 => Ok(Syscall::KernelGetInfo),
            1114 => Ok(Syscall::PkgInstall),
            1115 => Ok(Syscall::PkgRemove),
            1116 => Ok(Syscall::PkgQuery),
            1117 => Ok(Syscall::PkgList),
            1118 => Ok(Syscall::PkgUpdate),
            1124 => Ok(Syscall::TimeGetUptime),
            1125 => Ok(Syscall::TimeCreateTimer),
            1126 => Ok(Syscall::TimeCancelTimer),
            1225 => Ok(Syscall::FutexWait),
            1226 => Ok(Syscall::FutexWake),
            1229 => Ok(Syscall::ProcessGetenv),
            1234 => Ok(Syscall::ShmOpen),
            1235 => Ok(Syscall::ShmUnlink),
            1236 => Ok(Syscall::ShmTruncate),
            1249 => Ok(Syscall::SocketSend),
            1250 => Ok(Syscall::SocketRecv),
            1251 => Ok(Syscall::SocketClose),
            1254 => Ok(Syscall::FbGetInfo),
            1255 => Ok(Syscall::FbMap),
            1256 => Ok(Syscall::InputPoll),
            1257 => Ok(Syscall::InputRead),
            1258 => Ok(Syscall::FbSwap),
            1264 => Ok(Syscall::WlConnect),
            1265 => Ok(Syscall::WlDisconnect),
            1266 => Ok(Syscall::WlSendMessage),
            1267 => Ok(Syscall::WlRecvMessage),
            1268 => Ok(Syscall::WlCreateShmPool),
            1269 => Ok(Syscall::WlCreateSurface),
            1270 => Ok(Syscall::WlCommitSurface),
            1271 => Ok(Syscall::WlGetEvents),
            1298 => Ok(Syscall::TcSetPgrp),
            1299 => Ok(Syscall::TcGetPgrp),
            1304 => Ok(Syscall::OpenPty),
            1305 => Ok(Syscall::GrantPty),
            1306 => Ok(Syscall::UnlockPty),
            1307 => Ok(Syscall::PtsName),
            1344 => Ok(Syscall::AudioOpen),
            1345 => Ok(Syscall::AudioClose),
            1346 => Ok(Syscall::AudioWrite),
            1347 => Ok(Syscall::AudioSetVolume),
            1348 => Ok(Syscall::AudioGetInfo),
            1349 => Ok(Syscall::AudioStart),
            1350 => Ok(Syscall::AudioStop),
            1351 => Ok(Syscall::AudioPause),
            _ => Err(()),
        }
    }
}

impl Syscall {
    /// The Linux name of this call, or `None` for a VeridianOS-only call.
    pub const fn linux_name(self) -> Option<&'static str> {
        match self {
            Syscall::IpcSend => None,
            Syscall::IpcReceive => None,
            Syscall::IpcCall => None,
            Syscall::IpcReply => None,
            Syscall::IpcCreateEndpoint => None,
            Syscall::IpcBindEndpoint => None,
            Syscall::IpcShareMemory => None,
            Syscall::IpcMapMemory => None,
            Syscall::SchedYield => Some("sched_yield"),
            Syscall::ExitGroup => Some("exit_group"),
            Syscall::Fork => Some("fork"),
            Syscall::Vfork => Some("vfork"),
            Syscall::Execve => Some("execve"),
            Syscall::Wait4 => Some("wait4"),
            Syscall::Getpid => Some("getpid"),
            Syscall::Getppid => Some("getppid"),
            Syscall::ProcessSetPriority => None,
            Syscall::ProcessGetPriority => None,
            Syscall::Getcwd => Some("getcwd"),
            Syscall::Chdir => Some("chdir"),
            Syscall::Fchdir => Some("fchdir"),
            Syscall::Chroot => Some("chroot"),
            Syscall::Kill => Some("kill"),
            Syscall::Umask => Some("umask"),
            Syscall::Uname => Some("uname"),
            Syscall::ProcessGetenv => None,
            Syscall::Waitid => Some("waitid"),
            Syscall::Prctl => Some("prctl"),
            Syscall::Ptrace => Some("ptrace"),
            Syscall::Mmap => Some("mmap"),
            Syscall::Munmap => Some("munmap"),
            Syscall::Mprotect => Some("mprotect"),
            Syscall::Brk => Some("brk"),
            Syscall::Madvise => Some("madvise"),
            Syscall::Mremap => Some("mremap"),
            Syscall::MemfdCreate => Some("memfd_create"),
            Syscall::CapabilityGrant => None,
            Syscall::CapabilityRevoke => None,
            Syscall::ThreadCreate => None,
            Syscall::Exit => Some("exit"),
            Syscall::ThreadJoin => None,
            Syscall::Gettid => Some("gettid"),
            Syscall::ThreadSetAffinity => None,
            Syscall::ThreadGetAffinity => None,
            Syscall::Clone => Some("clone"),
            Syscall::Clone3 => Some("clone3"),
            Syscall::SetTidAddress => Some("set_tid_address"),
            Syscall::SetRobustList => Some("set_robust_list"),
            Syscall::GetRobustList => Some("get_robust_list"),
            Syscall::Rseq => Some("rseq"),
            Syscall::ArchPrctl => Some("arch_prctl"),
            Syscall::Tkill => Some("tkill"),
            Syscall::Tgkill => Some("tgkill"),
            Syscall::Open => Some("open"),
            Syscall::Openat => Some("openat"),
            Syscall::Close => Some("close"),
            Syscall::Read => Some("read"),
            Syscall::Write => Some("write"),
            Syscall::Lseek => Some("lseek"),
            Syscall::Pread64 => Some("pread64"),
            Syscall::Pwrite64 => Some("pwrite64"),
            Syscall::Readv => Some("readv"),
            Syscall::Writev => Some("writev"),
            Syscall::Fstat => Some("fstat"),
            Syscall::Stat => Some("stat"),
            Syscall::Lstat => Some("lstat"),
            Syscall::Newfstatat => Some("newfstatat"),
            Syscall::Statx => Some("statx"),
            Syscall::Statfs => Some("statfs"),
            Syscall::Fstatfs => Some("fstatfs"),
            Syscall::Ftruncate => Some("ftruncate"),
            Syscall::Truncate => Some("truncate"),
            Syscall::Fallocate => Some("fallocate"),
            Syscall::Dup => Some("dup"),
            Syscall::Dup2 => Some("dup2"),
            Syscall::Dup3 => Some("dup3"),
            Syscall::Pipe => Some("pipe"),
            Syscall::Pipe2 => Some("pipe2"),
            Syscall::Ioctl => Some("ioctl"),
            Syscall::Fcntl => Some("fcntl"),
            Syscall::Flock => Some("flock"),
            Syscall::Access => Some("access"),
            Syscall::Faccessat => Some("faccessat"),
            Syscall::Faccessat2 => Some("faccessat2"),
            Syscall::Chmod => Some("chmod"),
            Syscall::Fchmod => Some("fchmod"),
            Syscall::Fchmodat => Some("fchmodat"),
            Syscall::Chown => Some("chown"),
            Syscall::Fchown => Some("fchown"),
            Syscall::Fchownat => Some("fchownat"),
            Syscall::Mknod => Some("mknod"),
            Syscall::Rename => Some("rename"),
            Syscall::Renameat => Some("renameat"),
            Syscall::Link => Some("link"),
            Syscall::Linkat => Some("linkat"),
            Syscall::Symlink => Some("symlink"),
            Syscall::Symlinkat => Some("symlinkat"),
            Syscall::Readlink => Some("readlink"),
            Syscall::Readlinkat => Some("readlinkat"),
            Syscall::Utimensat => Some("utimensat"),
            Syscall::Unlink => Some("unlink"),
            Syscall::Unlinkat => Some("unlinkat"),
            Syscall::Poll => Some("poll"),
            Syscall::Ppoll => Some("ppoll"),
            Syscall::Select => Some("select"),
            Syscall::Pselect6 => Some("pselect6"),
            Syscall::Getdents64 => Some("getdents64"),
            Syscall::Mkdir => Some("mkdir"),
            Syscall::Mkdirat => Some("mkdirat"),
            Syscall::Rmdir => Some("rmdir"),
            Syscall::DirOpendir => None,
            Syscall::DirReaddir => None,
            Syscall::DirClosedir => None,
            Syscall::FsMount => None,
            Syscall::FsUnmount => None,
            Syscall::Sync => Some("sync"),
            Syscall::Fsync => Some("fsync"),
            Syscall::Fdatasync => Some("fdatasync"),
            Syscall::KernelGetInfo => None,
            Syscall::Sysinfo => Some("sysinfo"),
            Syscall::Getrusage => Some("getrusage"),
            Syscall::PkgInstall => None,
            Syscall::PkgRemove => None,
            Syscall::PkgQuery => None,
            Syscall::PkgList => None,
            Syscall::PkgUpdate => None,
            Syscall::TimeGetUptime => None,
            Syscall::TimeCreateTimer => None,
            Syscall::TimeCancelTimer => None,
            Syscall::ClockGettime => Some("clock_gettime"),
            Syscall::ClockGetres => Some("clock_getres"),
            Syscall::ClockNanosleep => Some("clock_nanosleep"),
            Syscall::Nanosleep => Some("nanosleep"),
            Syscall::Gettimeofday => Some("gettimeofday"),
            Syscall::RtSigaction => Some("rt_sigaction"),
            Syscall::RtSigprocmask => Some("rt_sigprocmask"),
            Syscall::RtSigsuspend => Some("rt_sigsuspend"),
            Syscall::RtSigreturn => Some("rt_sigreturn"),
            Syscall::RtSigpending => Some("rt_sigpending"),
            Syscall::Sigaltstack => Some("sigaltstack"),
            Syscall::Getuid => Some("getuid"),
            Syscall::Geteuid => Some("geteuid"),
            Syscall::Getgid => Some("getgid"),
            Syscall::Getegid => Some("getegid"),
            Syscall::Setuid => Some("setuid"),
            Syscall::Setgid => Some("setgid"),
            Syscall::Setreuid => Some("setreuid"),
            Syscall::Setregid => Some("setregid"),
            Syscall::Setresuid => Some("setresuid"),
            Syscall::Getresuid => Some("getresuid"),
            Syscall::Setresgid => Some("setresgid"),
            Syscall::Getresgid => Some("getresgid"),
            Syscall::Getgroups => Some("getgroups"),
            Syscall::Setgroups => Some("setgroups"),
            Syscall::Setpgid => Some("setpgid"),
            Syscall::Getpgid => Some("getpgid"),
            Syscall::Getpgrp => Some("getpgrp"),
            Syscall::Setsid => Some("setsid"),
            Syscall::Getsid => Some("getsid"),
            Syscall::TcSetPgrp => None,
            Syscall::TcGetPgrp => None,
            Syscall::SchedSetscheduler => Some("sched_setscheduler"),
            Syscall::SchedGetscheduler => Some("sched_getscheduler"),
            Syscall::SchedSetparam => Some("sched_setparam"),
            Syscall::SchedGetparam => Some("sched_getparam"),
            Syscall::SchedSetattr => Some("sched_setattr"),
            Syscall::SchedGetattr => Some("sched_getattr"),
            Syscall::SchedGetPriorityMax => Some("sched_get_priority_max"),
            Syscall::SchedGetPriorityMin => Some("sched_get_priority_min"),
            Syscall::SchedRrGetInterval => Some("sched_rr_get_interval"),
            Syscall::SchedSetaffinity => Some("sched_setaffinity"),
            Syscall::SchedGetaffinity => Some("sched_getaffinity"),
            Syscall::Getpriority => Some("getpriority"),
            Syscall::Setpriority => Some("setpriority"),
            Syscall::Futex => Some("futex"),
            Syscall::FutexWait => None,
            Syscall::FutexWake => None,
            Syscall::ShmOpen => None,
            Syscall::ShmUnlink => None,
            Syscall::ShmTruncate => None,
            Syscall::Socket => Some("socket"),
            Syscall::Bind => Some("bind"),
            Syscall::Listen => Some("listen"),
            Syscall::Connect => Some("connect"),
            Syscall::Accept => Some("accept"),
            Syscall::Accept4 => Some("accept4"),
            Syscall::SocketSend => None,
            Syscall::SocketRecv => None,
            Syscall::SocketClose => None,
            Syscall::Socketpair => Some("socketpair"),
            Syscall::Sendto => Some("sendto"),
            Syscall::Recvfrom => Some("recvfrom"),
            Syscall::Getsockname => Some("getsockname"),
            Syscall::Getpeername => Some("getpeername"),
            Syscall::Setsockopt => Some("setsockopt"),
            Syscall::Getsockopt => Some("getsockopt"),
            Syscall::Sendmsg => Some("sendmsg"),
            Syscall::Recvmsg => Some("recvmsg"),
            Syscall::FbGetInfo => None,
            Syscall::FbMap => None,
            Syscall::InputPoll => None,
            Syscall::InputRead => None,
            Syscall::FbSwap => None,
            Syscall::WlConnect => None,
            Syscall::WlDisconnect => None,
            Syscall::WlSendMessage => None,
            Syscall::WlRecvMessage => None,
            Syscall::WlCreateShmPool => None,
            Syscall::WlCreateSurface => None,
            Syscall::WlCommitSurface => None,
            Syscall::WlGetEvents => None,
            Syscall::Getrlimit => Some("getrlimit"),
            Syscall::Setrlimit => Some("setrlimit"),
            Syscall::Prlimit64 => Some("prlimit64"),
            Syscall::EpollCreate => Some("epoll_create"),
            Syscall::EpollCreate1 => Some("epoll_create1"),
            Syscall::EpollCtl => Some("epoll_ctl"),
            Syscall::EpollWait => Some("epoll_wait"),
            Syscall::EpollPwait => Some("epoll_pwait"),
            Syscall::EpollPwait2 => Some("epoll_pwait2"),
            Syscall::OpenPty => None,
            Syscall::GrantPty => None,
            Syscall::UnlockPty => None,
            Syscall::PtsName => None,
            Syscall::AudioOpen => None,
            Syscall::AudioClose => None,
            Syscall::AudioWrite => None,
            Syscall::AudioSetVolume => None,
            Syscall::AudioGetInfo => None,
            Syscall::AudioStart => None,
            Syscall::AudioStop => None,
            Syscall::AudioPause => None,
            Syscall::Getrandom => Some("getrandom"),
            Syscall::Eventfd => Some("eventfd"),
            Syscall::Eventfd2 => Some("eventfd2"),
            Syscall::TimerfdCreate => Some("timerfd_create"),
            Syscall::TimerfdSettime => Some("timerfd_settime"),
            Syscall::TimerfdGettime => Some("timerfd_gettime"),
            Syscall::Signalfd => Some("signalfd"),
            Syscall::Signalfd4 => Some("signalfd4"),
            Syscall::InotifyInit1 => Some("inotify_init1"),
            Syscall::InotifyAddWatch => Some("inotify_add_watch"),
            Syscall::InotifyRmWatch => Some("inotify_rm_watch"),
        }
    }
}

/// Every call, for table checks.
#[cfg(test)]
pub(crate) const ALL: &[Syscall] = &[
    Syscall::IpcSend,
    Syscall::IpcReceive,
    Syscall::IpcCall,
    Syscall::IpcReply,
    Syscall::IpcCreateEndpoint,
    Syscall::IpcBindEndpoint,
    Syscall::IpcShareMemory,
    Syscall::IpcMapMemory,
    Syscall::SchedYield,
    Syscall::ExitGroup,
    Syscall::Fork,
    Syscall::Vfork,
    Syscall::Execve,
    Syscall::Wait4,
    Syscall::Getpid,
    Syscall::Getppid,
    Syscall::ProcessSetPriority,
    Syscall::ProcessGetPriority,
    Syscall::Getcwd,
    Syscall::Chdir,
    Syscall::Fchdir,
    Syscall::Chroot,
    Syscall::Kill,
    Syscall::Umask,
    Syscall::Uname,
    Syscall::ProcessGetenv,
    Syscall::Waitid,
    Syscall::Prctl,
    Syscall::Ptrace,
    Syscall::Mmap,
    Syscall::Munmap,
    Syscall::Mprotect,
    Syscall::Brk,
    Syscall::Madvise,
    Syscall::Mremap,
    Syscall::MemfdCreate,
    Syscall::CapabilityGrant,
    Syscall::CapabilityRevoke,
    Syscall::ThreadCreate,
    Syscall::Exit,
    Syscall::ThreadJoin,
    Syscall::Gettid,
    Syscall::ThreadSetAffinity,
    Syscall::ThreadGetAffinity,
    Syscall::Clone,
    Syscall::Clone3,
    Syscall::SetTidAddress,
    Syscall::SetRobustList,
    Syscall::GetRobustList,
    Syscall::Rseq,
    Syscall::ArchPrctl,
    Syscall::Tkill,
    Syscall::Tgkill,
    Syscall::Open,
    Syscall::Openat,
    Syscall::Close,
    Syscall::Read,
    Syscall::Write,
    Syscall::Lseek,
    Syscall::Pread64,
    Syscall::Pwrite64,
    Syscall::Readv,
    Syscall::Writev,
    Syscall::Fstat,
    Syscall::Stat,
    Syscall::Lstat,
    Syscall::Newfstatat,
    Syscall::Statx,
    Syscall::Statfs,
    Syscall::Fstatfs,
    Syscall::Ftruncate,
    Syscall::Truncate,
    Syscall::Fallocate,
    Syscall::Dup,
    Syscall::Dup2,
    Syscall::Dup3,
    Syscall::Pipe,
    Syscall::Pipe2,
    Syscall::Ioctl,
    Syscall::Fcntl,
    Syscall::Flock,
    Syscall::Access,
    Syscall::Faccessat,
    Syscall::Faccessat2,
    Syscall::Chmod,
    Syscall::Fchmod,
    Syscall::Fchmodat,
    Syscall::Chown,
    Syscall::Fchown,
    Syscall::Fchownat,
    Syscall::Mknod,
    Syscall::Rename,
    Syscall::Renameat,
    Syscall::Link,
    Syscall::Linkat,
    Syscall::Symlink,
    Syscall::Symlinkat,
    Syscall::Readlink,
    Syscall::Readlinkat,
    Syscall::Utimensat,
    Syscall::Unlink,
    Syscall::Unlinkat,
    Syscall::Poll,
    Syscall::Ppoll,
    Syscall::Select,
    Syscall::Pselect6,
    Syscall::Getdents64,
    Syscall::Mkdir,
    Syscall::Mkdirat,
    Syscall::Rmdir,
    Syscall::DirOpendir,
    Syscall::DirReaddir,
    Syscall::DirClosedir,
    Syscall::FsMount,
    Syscall::FsUnmount,
    Syscall::Sync,
    Syscall::Fsync,
    Syscall::Fdatasync,
    Syscall::KernelGetInfo,
    Syscall::Sysinfo,
    Syscall::Getrusage,
    Syscall::PkgInstall,
    Syscall::PkgRemove,
    Syscall::PkgQuery,
    Syscall::PkgList,
    Syscall::PkgUpdate,
    Syscall::TimeGetUptime,
    Syscall::TimeCreateTimer,
    Syscall::TimeCancelTimer,
    Syscall::ClockGettime,
    Syscall::ClockGetres,
    Syscall::ClockNanosleep,
    Syscall::Nanosleep,
    Syscall::Gettimeofday,
    Syscall::RtSigaction,
    Syscall::RtSigprocmask,
    Syscall::RtSigsuspend,
    Syscall::RtSigreturn,
    Syscall::RtSigpending,
    Syscall::Sigaltstack,
    Syscall::Getuid,
    Syscall::Geteuid,
    Syscall::Getgid,
    Syscall::Getegid,
    Syscall::Setuid,
    Syscall::Setgid,
    Syscall::Setreuid,
    Syscall::Setregid,
    Syscall::Setresuid,
    Syscall::Getresuid,
    Syscall::Setresgid,
    Syscall::Getresgid,
    Syscall::Getgroups,
    Syscall::Setgroups,
    Syscall::Setpgid,
    Syscall::Getpgid,
    Syscall::Getpgrp,
    Syscall::Setsid,
    Syscall::Getsid,
    Syscall::TcSetPgrp,
    Syscall::TcGetPgrp,
    Syscall::SchedSetscheduler,
    Syscall::SchedGetscheduler,
    Syscall::SchedSetparam,
    Syscall::SchedGetparam,
    Syscall::SchedSetattr,
    Syscall::SchedGetattr,
    Syscall::SchedGetPriorityMax,
    Syscall::SchedGetPriorityMin,
    Syscall::SchedRrGetInterval,
    Syscall::SchedSetaffinity,
    Syscall::SchedGetaffinity,
    Syscall::Getpriority,
    Syscall::Setpriority,
    Syscall::Futex,
    Syscall::FutexWait,
    Syscall::FutexWake,
    Syscall::ShmOpen,
    Syscall::ShmUnlink,
    Syscall::ShmTruncate,
    Syscall::Socket,
    Syscall::Bind,
    Syscall::Listen,
    Syscall::Connect,
    Syscall::Accept,
    Syscall::Accept4,
    Syscall::SocketSend,
    Syscall::SocketRecv,
    Syscall::SocketClose,
    Syscall::Socketpair,
    Syscall::Sendto,
    Syscall::Recvfrom,
    Syscall::Getsockname,
    Syscall::Getpeername,
    Syscall::Setsockopt,
    Syscall::Getsockopt,
    Syscall::Sendmsg,
    Syscall::Recvmsg,
    Syscall::FbGetInfo,
    Syscall::FbMap,
    Syscall::InputPoll,
    Syscall::InputRead,
    Syscall::FbSwap,
    Syscall::WlConnect,
    Syscall::WlDisconnect,
    Syscall::WlSendMessage,
    Syscall::WlRecvMessage,
    Syscall::WlCreateShmPool,
    Syscall::WlCreateSurface,
    Syscall::WlCommitSurface,
    Syscall::WlGetEvents,
    Syscall::Getrlimit,
    Syscall::Setrlimit,
    Syscall::Prlimit64,
    Syscall::EpollCreate,
    Syscall::EpollCreate1,
    Syscall::EpollCtl,
    Syscall::EpollWait,
    Syscall::EpollPwait,
    Syscall::EpollPwait2,
    Syscall::OpenPty,
    Syscall::GrantPty,
    Syscall::UnlockPty,
    Syscall::PtsName,
    Syscall::AudioOpen,
    Syscall::AudioClose,
    Syscall::AudioWrite,
    Syscall::AudioSetVolume,
    Syscall::AudioGetInfo,
    Syscall::AudioStart,
    Syscall::AudioStop,
    Syscall::AudioPause,
    Syscall::Getrandom,
    Syscall::Eventfd,
    Syscall::Eventfd2,
    Syscall::TimerfdCreate,
    Syscall::TimerfdSettime,
    Syscall::TimerfdGettime,
    Syscall::Signalfd,
    Syscall::Signalfd4,
    Syscall::InotifyInit1,
    Syscall::InotifyAddWatch,
    Syscall::InotifyRmWatch,
];
