// RISC-V-specific bootstrap output functions
//
// Uses the kernel println! macro (backed by SBI console) for serial
// output during boot.  The stage functions are generated by the shared
// `define_bootstrap_stages!` macro to avoid duplicating identical stage
// messages across architectures.

#[allow(unused_imports)]
use crate::println;

/// Print a bootstrap message via RISC-V SBI console.
macro_rules! riscv_boot_print {
    ($s:expr) => {
        println!($s)
    };
}

crate::define_bootstrap_stages!(riscv_boot_print);
